#!/usr/bin/env python3
"""Generate .claude/skills/SKILLS.md — the two-tier skill index.

Built from each SKILL.md's frontmatter (single source of truth):
  - tier: user   → "Your commands" — you invoke these with /<name>.
  - tier: agent  → "Auto-applied doctrine" — the agent self-invokes these during
    work; the skill_router_hook surfaces them from their `triggers`. You never
    pick these.

This file is on-demand (not loaded into every session), so keeping the full map
here instead of in CLAUDE.md is a per-session token saving. Re-run after adding
or retiering a skill:  rtk python3 tools/memory/gen_skills_index.py
"""

from __future__ import annotations

from pathlib import Path

from skill_router_hook import _parse_frontmatter  # same package (tools/memory)

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
OUT_PATH = SKILLS_DIR / "SKILLS.md"


def _one_line_desc(desc: str, cap: int = 140) -> str:
    d = " ".join(desc.split())
    return (d[: cap - 1].rstrip() + "…") if len(d) > cap else d


def collect() -> tuple[list[tuple[str, str]], list[tuple[str, str, list[str]]]]:
    user: list[tuple[str, str]] = []
    agent: list[tuple[str, str, list[str]]] = []
    for p in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        fm = _parse_frontmatter(p.read_text(encoding="utf-8"))
        name = p.parent.name
        desc = _one_line_desc(fm.get("description", ""))
        if fm.get("tier") == "user":
            user.append((name, desc))
        elif fm.get("tier") == "agent":
            agent.append((name, desc, fm.get("triggers", [])))
    return user, agent


def render(user, agent) -> str:
    out: list[str] = []
    out.append("# Skills index")
    out.append("")
    out.append("<!-- GENERATED by tools/memory/gen_skills_index.py from each SKILL.md")
    out.append("     frontmatter. Do not edit by hand — edit the SKILL.md and re-run. -->")
    out.append("")
    out.append("Two tiers. **You only ever pick the first group.** Everything in the second")
    out.append("group is doctrine the agent self-invokes at the right moment — surfaced")
    out.append("automatically by `tools/memory/skill_router_hook.py` from each skill's")
    out.append("`triggers`. If you are ever unsure which to use: you almost certainly want")
    out.append("nothing — describe the problem and the agent routes itself.")
    out.append("")
    out.append("## Your commands (`/<name>`)")
    out.append("")
    out.append("The only skills meant for you to invoke directly.")
    out.append("")
    for name, desc in user:
        out.append(f"- **`/{name}`** — {desc}")
    out.append("")
    out.append("## Auto-applied doctrine (agent self-invokes)")
    out.append("")
    out.append("You do not pick these. They fire on what the agent is doing / on trigger")
    out.append("words in your message. Listed for transparency, not as a to-do.")
    out.append("")
    out.append("| Skill | What it covers | Example triggers |")
    out.append("|---|---|---|")
    for name, desc, triggers in agent:
        ex = ", ".join(f"`{t}`" for t in triggers[:5])
        out.append(f"| `{name}` | {desc} | {ex} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    user, agent = collect()
    OUT_PATH.write_text(render(user, agent), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)} — {len(user)} user, {len(agent)} agent skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
