#!/usr/bin/env bash
# post-checkout hook — auto-trust RTK project filters in this worktree.
# Prevents the "[rtk] WARNING: untrusted project filters" prefix from
# appearing in commit messages generated by generate_lift_commit.py.
REPO_ROOT="$(git rev-parse --show-toplevel)"
if [ -f "$REPO_ROOT/.rtk/filters.toml" ] && command -v rtk >/dev/null 2>&1; then
    rtk trust >/dev/null 2>&1 || true
fi
exit 0
