| function | addr | source_file | screen_result | vc71 | action | reason |
|----------|------|-------------|---------------|------|--------|--------|
| FUN_00113160 | 0x113160 | real_math.c | pass | 93.3% | committed | zlib gzerror, §10 arg-misgroup fix |
| FUN_00109a60 | 0x109a60 | real_math.c | screen:pass | 76.4% | reverted | matrix_inverse, confirmed structural ceiling (Opus+permuter) |
| FUN_000d1540 | 0xd1540 | hud.c | screen:fail | - | skipped | unaff_EBP register-arg artifact |
| FUN_00112fc0 | 0x112fc0 | real_math.c | pass | 95.8% | committed | zlib gzflush; FUN_00112f00 has @eax found |
| FUN_00113740 | 0x113740 | real_math.c | pass | 85.4% | committed | zlib gzgets; self-store ceiling |
| FUN_00111170 | 0x111170 | real_math.c | pass | 88.6% | committed | zlib inflateEnd; goto improved 85→88.6% |
| FUN_001137a0 | 0x1137a0 | real_math.c | pass | 93.0% | committed | zlib gzseek; all callees accessible |
| FUN_001108b0 | 0x1108b0 | real_math.c | pass | 97.1% | committed | vector_tree BST search/insert |
| FUN_00110b40 | 0x110b40 | real_math.c | pass | 94.3% | committed | zlib compress2; goto 79.7→94.3% |
| FUN_001139d0 | 0x1139d0 | real_math.c | pass | 100% | committed | inflate_blocks_new |
| FUN_00113930 | 0x113930 | real_math.c | pass | 100% | committed | inflate_blocks_reset (bonus fix) |
| FUN_00111220 | 0x111220 | real_math.c | pass | 88.1% | committed | deflateCopy; memcpy+goto 71→88% |
| FUN_0010e4d0 | 0x10e4d0 | real_math.c | pass | 99.5% | committed | vector_intersects_triangle2d pure leaf |
| FUN_001108b0 | 0x1108b0 | real_math.c | pass | 97.1% | committed | vector_tree BST |
| FUN_00110b40 | 0x110b40 | real_math.c | pass | 94.3% | committed | compress2; goto 79→94% |
| FUN_001127e0 | 0x1127e0 | real_math.c | pass | 100% | committed | gzread |
| vector_to_line_distance_squared3d | 0x10ce10 | real_math.c | equiv:15/60 | n/a | dormant-verdict | FP-order branch-flip NOT clamp/arg bug (instruction-proven 2026-06-30); s/t/classification/call-args all byte-faithful; FUN_0010cd40 preserves EDX so t_oob arg2=p1 correct; keep dormant |
| accelerate_to_position | 0x10f5b0 | real_math.c | equiv:53/100 | 37.9% | committed 9cf215be | 1D motion integrator; fresh lift (void(void)->8-arg cdecl char-return recovered from disasm); VC71 fabsf/sqrtf-as-MSVC-call cap; equiv finite-clean (all 47 fails inf/nan corners); reviewer AUTO_ACCEPT |
| FUN_001122e0 deflateParams | 0x1122e0 | real_math.c | n/a | 90.3% | committed (deflateParams) | zlib level/strategy setter; indirect config_table[level].func(s,Z_BLOCK); @reg callees putShortMSB/flush_pending verified vs disasm; reviewer AUTO_ACCEPT |

## Build status 2026-06-30
GREEN (patched default.xbe builds). Fixed pre-existing multi-layer breakage: commits d27805f7 (decl.h mangled-name skip), f1db5bdb (128 stale FUN_ renames), 2222fd89 (xboxkrnl.h XBAPI extern + generator skip of kernel-header decls + 6 ported-without-impl stubs allowlisted). real_math.obj: 132/171 ported, 39 remaining.

| FUN_00112590 deflateInit2_ | 0x112590 | real_math.c | reviewer:1:1-disasm | (ref stale) | committed 6a6e8b64 | zlib deflate-stream allocator/init; indirect zalloc(opaque,items,size)x5, deflate_state field init, deflateReset deferral; fixed FUN_00112260 decl void->int(int strm); reviewer AUTO_ACCEPT via 1:1 cachebeta disasm audit; VC71 DEFERRED (stale 54-insn whole-file stub; fresh delinked/functions/00112590.obj exported, needs objdiff.json registration) |

| FUN_00112f00 gz_flush | 0x112f00 | real_math.c | reviewer:1:1-disasm | @eax-capped | committed | gzip-write flush internal (@<eax>=gz); deflate-loop + fwrite drain; reviewer AUTO_ACCEPT 1:1 disasm; VC71 capped (@eax prologue + no ref); fresh delinked/functions/00112f00.obj exported |

## real_math.obj progress: 141/171 ported, 30 remaining (this session: +11; added deflateReset 0x112260). gzio get/put/open/close/destroy wrappers DONE.
## NEXT (31 remaining, all bigger/entangled — need fresh context per lift):
##  - gzopen INTERNAL 0x113230 (@<eax> mode; parses mode/allocs gz/opens file/reads header — medium)
##  - check_header 0x1128c0 (~150 insns, get_byte inlined ~10x), gzread 0x1134e0 (calls check_header+inflate), deflate 0x110ed0 (~200, cdecl, callees ready)
##  - void(void) sig-recovery: 0x110650 0x110820 0x1113c0 0x111420 0x1114a0 0x1116b0 0x111770 0x111910 0x111ba0 0x111ea0 0x112260(deflateReset, decl already fixed to int(int)) — each needs disasm ABI recovery
##  - FP equiv-only (fabsf/x87-capped): 0x109f40 euler, 0x10a5e0/0x10a710 transition
##  - dormant/parked: 0x10ce10 (FP branch-flip), 0x110d40, 0x109a60 matrix_inverse (proven ceiling, skip), 0x10a830 (@<ebx>)
##  - low-addr object fns (NOT pure math — datum_get/tag_get callees, stateful, crash-risk): 0x1ada0 0x1aeb0 0x1b280 0x1b750
## PROVEN PATTERNS this session (all reg-arg ABIs work): reg-defined (@<eax>/@<ebx>/@<esi> incoming) -> add @<reg> to kb decl, extract_reg_args --apply (baseline tools/kb_reg_baseline.json), VC71 capped (reviewer 1:1 disasm audit is the gate). Calling @<reg> functions from C -> build's reg-arg-call mechanism (correct at runtime; cl.exe/VC71 emits cdecl so VC71 capped for callers too). Per-fn delinked refs: ghidra-live export range start-nextfn (whole-file delinked/real_math.obj is STALE for newer fns); objdiff-registration FOLLOWUP for accurate VC71 numbers. Staging: git add BEFORE generate_lift_commit.py.
## REMAINING (34) are the bigger/entangled tail — need fresh context per lift:
##  - check_header 0x1128c0 (~150 insns, get_byte inlined ~10x; gzip header parse) — big but mechanical
##  - gz_destroy 0x112cd0 (@<esi>, ~30 insns; callees debug_free/inflateEnd 0x115430/deflateEnd 0x111170 all PORTED+ready; needs _fclose decl + final-free args from disasm) — TRACTABLE, good next pick
##  - 0x113110 (calls 0x112cd0/0x112f00/0x1130a0 — now 2 of 3 ported), 0x1134e0 gzread (calls check_header+inflate), 0x113480, 0x110650/0x110820/etc void(void) sig-recovery, deflate 0x110ed0 (~200 insns cdecl, callees ready)
##  - FP (equiv-only): 0x109f40 euler, 0x10a5e0/0x10a710 transition; dormant: 0x10ce10/0x110d40/0x109a60(matrix_inverse, proven ceiling — skip)
## REG-ARG pattern PROVEN this session: @<eax>/@<ebx>/@<esi> incoming all work (precedent 0x36890/0x3cb50/0x3b7e0); add @<reg> to kb decl + run extract_reg_args --apply (baseline tools/kb_reg_baseline.json) + reviewer 1:1 disasm audit (VC71 capped for reg-defined). Per-function delinked refs: export via mcp ghidra-live for range start-nextfn, then objdiff-register (FOLLOWUP, not done) for VC71 numbers.
## STAGING GOTCHA: `git add` the lift files BEFORE running generate_lift_commit.py (it audits the staged set); a bad pathspec aborts the whole add. baseline is tools/kb_reg_baseline.json (NOT tools/audit/).
## CLEANUP NOTE: kb 0x1db2b3 is named "_fread" but is actually FWRITE (Ghidra FID_conflict; fread/fwrite share sig). Calls resolve to correct addr/ABI (machine-identical) so non-blocking, but rename kb decl + call sites (real_math.c ~4448/4485/4568 + the gz functions) to fwrite_0x1db2b3 for clarity to avoid read/write confusion.
## FOLLOW-UP: register delinked/functions/00112590.obj in tools/verify/objdiff.json for VC71 byte-match number (like commit cff9c426 did for 1122e0/1127e0/111220). The stale whole-file delinked/real_math.obj (26 syms) gives wrong refs for newer functions — prefer per-function refs + objdiff registration.

## Next-target queue (zlib integer, ≥90%-VC71 achievable; build green so verify normally)
- ENTANGLED (callee ABI recovery needed first): 0x1134e0 gzread (needs FUN_001130d0/001128c0 @reg recovery), 0x113a90 (FID_conflict:_fwprintf CRT callee).
- CLEAN-ish callees: 0x110ed0 deflate (big, ~200 insns; callees 110e40/110e70 @reg in kb + ported), 0x112590 deflateInit2_ (8 args).
- REG-ARG (need kb @reg): 0x10a830, 0x112f00, 0x113230.
- FP (equiv-only, fabsf-capped): 0x109f40, 0x10a5e0, 0x10a710.
- Note: zlib FID_conflict CRT callees may need renaming like _fread/_rewind/_fseek did. void(void) callees need disasm @reg recovery before calling.
- ANALYST AGENT UNRELIABLE: xbox-halo-re-analyst stalled 3x ("Response stalled mid-stream") — do lifts inline; lift-reviewer agent works (AUTO_ACCEPT on both lifts).

## Session 2026-06-30 (cont): real_math.obj 143->146/171, 25 remaining
| read_buf | 0x1113c0 | real_math.c | reviewer:AUTO_ACCEPT 1:1 | 94.7% (50/45) | committed | zlib deflate input reader; @<edi>=strm,@<ecx>=size,stack buf; +5 reg prologue ceiling; LCS=45 all ref insns matched |
| putShortMSB | 0x110e40 | real_math.c | reviewer:AUTO_ACCEPT 1:1 | 87.8% (23/18) | committed | append 16-bit MSB-first to pending_buf (2 post-inc put_byte); @<ecx>=byte_val,@<eax>=state |
| flush_pending | 0x110e70 | real_math.c | reviewer:AUTO_ACCEPT 1:1 | 88.9% (41/40) | committed | drain pending_buf->next_out capped@avail_out; @<eax>=strm (kb decl misnames "state"); reviewer verified strm+0x10/state+0x10 base-distinct |
## NOTE: VC71 per-fn refs exported (delinked/functions/001113c0,00110e40,00110e70.obj — gitignored). Wide 0010f5b0.obj happens to span 0x10f5b0..0x113xxx so VC71 isolates these by symbol either way.
## DEFLATE (0x110ed0) callees putShortMSB+flush_pending NOW PORTED -> deflate unblocked (big ~200 insns, cdecl int(void*strm,int flush)).

## deflate (0x110ed0) — THE cluster centerpiece, committed pending reviewer re-verdict
| deflate | 0x110ed0 | real_math.c | reviewer semantic=PASS (re-verdict pending) | 91.6% (255/234) | staged | zlib deflate() driver/state-machine; CDECL (real gate, advisor: >=90% validates flatten); all reg-arg putShortMSB/flush_pending call sites recovered from disasm; goto-flatten cluster 0x111005-0x111046 proven equiv by reviewer; advisor pre-verified full trace |
## OBJDIFF REGISTRATION DONE this session: added 00110e40/00110e70/00110ed0/001113c0 units to objdiff.json (cff9c426 precedent) -> dedicated per-fn refs now deterministic (resolves reviewer reproducibility blocker for ALL session lifts; the 3 already-committed read_buf/putShortMSB/flush_pending are retroactively reproducible via these registrations).
## real_math.obj: 147/171 ported (read_buf+putShortMSB+flush_pending+deflate), 24 remaining.
## NEXT after deflate: 0x1128c0 check_header (~150 insns gzip header parse), 0x1134e0 gzread (calls check_header+inflate), 0x113230 gzopen-internal @<eax>, 0x113a90 inflate_codes_free-ish int(int,int*,int), void(void) sig-recovery (0x110650/0x110820/0x1116b0/0x111770/0x111910/0x111ba0/0x111ea0/0x1114a0 longest_match-big), FP equiv-only (0x109f40/0x10a5e0/0x10a710/0x10f770/0x10fa30), dormant (0x109a60 SKIP/0x110d40/0x10a830/0x10ce10), low-addr stateful (0x1ada0/0x1aeb0/0x1b280/0x1b750).

## ===== REMAINING-TAIL ASSESSMENT (probed 2026-06-30, real_math.obj 147/171, 24 left) =====
## Clean integer-zlib >=90% wins are EXHAUSTED. Remaining each need DEDICATED fresh context:
## BIG/INTRICATE (multi-state, many callees — verify callee ported-status first):
##   0x113a90 inflate_blocks: HUGE ~270-line block state machine (10-case switch on *state, stored/fixed/dynamic blocks, Huffman tree build via FUN_00116010/001160c0/001146e0/00116250, zalloc/zfree via piVar4[8]/[9] indirect, FUN_00116280 inflate_flush, FUN_00114740/00114f60). Decl int(int codes,int* z,int r). Biggest in cluster.
##   0x1114a0 longest_match: ~60-insn 8-byte-unrolled hot match loop, @<eax>=state, FUN_00117a80 asserts.
##   0x1128c0 check_header ~150 insns gzip header parse (get_byte inlined ~10x).
##   0x1134e0 gzread (calls check_header + inflate). 0x113230 gzopen-internal @<eax>=mode.
## FP equiv-only (x87 float10, fabsf/sqrtf-MSVC-call VC71-capped -> use /verify equivalence not VC71):
##   0x110650 __thiscall float motion helper (calls accelerate_to_position 0x10f5b0, FUN_001daf7e fmod); 0x109f40 euler(float* matrix,float* euler); 0x10a5e0/0x10a710 transition_function_evaluate(short,float); 0x10f770 angular_accelerate_to_position; 0x10fa30 accerate_to_position3d.
## DEBUG/CRT-variadic (fiddly, low value):
##   0x1116b0 check_match: __fastcall @<eax>=length+@<ecx>=match+@<edx>=start+stack s; variadic FID_conflict__fwprintf (NOT cleanly in kb; only _vfwprintf 0x1dc9a3 void(void) + _fputc 0x1db6c7) + garbled wide fmt strings + csmemcmp(0x8da40)+assert(0x117a80). z_verbose=DAT_00320e30. Mostly no-op in release but does memcmp+assert always.
## OTHER void(void) still UNPROBED: 0x110820 0x111770 0x111910 0x111ba0 0x111ea0.
## DORMANT/PARKED: 0x109a60 matrix_inverse (PROVEN structural ceiling 76.4% — SKIP), 0x110d40 int(int,int,uint), 0x10a830 @<ebx>, 0x10ce10 FP-branch-flip (dormant verdict, keep).
## LOW-ADDR stateful (NOT pure math — datum/tag callees, crash-risk, need runtime gate): 0x1ada0 0x1aeb0 0x1b280 0x1b750 char(int actor,int,short seat,short* action).
## RECOMMENDED next-window order: probe 0x110820/0x111770/0x111910/0x111ba0/0x111ea0 for any clean integer helper FIRST (fast wins); then FP cluster via equivalence gate; then big inflate_blocks/longest_match/check_header with fresh context each; defer low-addr stateful + check_match.

| callback-iterator | 0x110820 | real_math.c | reviewer:AUTO_ACCEPT instr-by-instr | 78.1% (36/28) | committed | bounded predicate iterator; reg-defined @<eax>start/@<ebx>passthru/@<esi>obj+stack param_1; decompiler under-counted 4-arg callback + missed EBX passthru (recovered from disasm); 78.1% = reg-prologue ceiling (all 28 ref body insns matched), NOT a bug |
## real_math.obj: 148/171 ported, 23 remaining. SESSION TOTAL this round: +5 (read_buf, putShortMSB, flush_pending, deflate@91.6%, callback-iterator). 0x110820 was already objdiff-registered from a prior session.

## PRE-ANALYZED next target: 0x111770 = fill_window (zlib deflate), @<esi>=state, void(void)->void(int state @<esi>). ~80 lines integer-only:
##   Outer do-while: more = window_size(s[0xd]) - strstart(s[0x19]) - lookahead(s[0x1b]);
##   if more==0 && strstart==0 && lookahead==0 -> more stays 0; if more==-1(0xffffffff) more=-2(wraparound guard);
##   WINDOW SLIDE when strstart >= w_size+MAX_DIST i.e. (s[9]-0x106)+s[9] <= strstart:
##     csmemcpy(s[0xc]=window, window+wsize, wsize); match_start(s[0x1a])-=wsize; block_start(s[0x15])-=wsize; strstart-=wsize;
##     REBASE head[] (s[0xf], hash_size=s[0x11] entries) and prev[] (s[0xe], wsize=s[9] entries): each h = (h<wsize)?0:h-wsize (ushort);
##     more += wsize.
##   read input (inline read_buf): n=min(more, avail_in s.strm[1]); if avail_in: if(state->wrap s[7]+0x18==0) adler=FUN_00110a10(adler,next_in,n); csmemcpy(window+strstart+lookahead, next_in, n); next_in+=n; total_in+=n; lookahead(s[0x1b])+=n;
##   if lookahead>=MIN_MATCH(3): ins_h = window[strstart]; ins_h = ((ins_h<<s.hash_shift[0x14]) ^ window[strstart+1]) & s.hash_mask[0x13]; (s[0x10]=ins_h)
##   assert "more < 2" via FUN_00117a80 if more<2. Loop while lookahead<MIN_LOOKAHEAD(0x106) && strm->avail_in!=0 (s[0]+4).
##   state offsets (int idx): [0]strm [9]w_size [0xc]window [0xd]window_size [0xe]prev [0xf]head [0x10]ins_h [0x11]hash_size [0x13]hash_mask [0x14]hash_shift [0x15]block_start [0x19]strstart [0x1a]match_start [0x1b]lookahead. Callees FUN_00110a10(adler)+csmemcpy+FUN_00117a80 all ported. @<esi>-defined -> VC71-capped, reviewer 1:1 is gate. GET DISASM first to confirm offsets+@<esi>+ the slide condition + adler arg order.

## fill_window (0x111770) — DEFERRED (stash@{0}), NOT committed.
## Reviewer instruction-level body audit = FULLY PASS (every offset, both rebase loops non-swapped head@0x3c/prev@0x38, all 7 control-flow points, all call-arg orders, assert unsigned polarity, ins_h dual-store). VC71 78.7% (157/158) = @<esi> reg-defined ceiling + benign scheduling (NOT a body bug). BUT reviewer verdict = NEEDS_RUNTIME (sub-90% + informative VC71 + complex memory-walking deflate path). Equivalence (unicorn_diff --allow-stubs --mem-trace): 140 seeds 0 fail but only 17.4% coverage (early-exit only; zero-fill avail_in=0 -> immediate return; concolic can't synthesize valid window/head/prev pointers). Main slide/rebase/read paths NOT runtime-covered.
## DECISION: deferred rather than activate an unverified-at-runtime function that deflate (committed, 91.6%) routes through (deflate->config-table deflate_fast/slow->fill_window). Original proven code keeps running. Full lift preserved in stash@{0} + complete disasm map in the PRE-ANALYZED block above.
## TO FINALIZE fill_window later: get a deflate-active state snapshot (xemu during compression, or golden harness src/halo/test_harness.c with a real deflate_state) -> unicorn_diff --state-snapshot OR golden test -> if clean, `git stash pop stash@{0}`, rebuild, re-run reviewer for AUTO_ACCEPT, commit.
## ===== ROUND-END STATE: real_math.obj 148/171 committed (read_buf 94.7%, putShortMSB 87.8%, flush_pending 88.9%, deflate 91.6%, callback-iterator 78.1% — all reviewer AUTO_ACCEPT). fill_window deferred. 23 unported remain (see REMAINING-TAIL ASSESSMENT above). =====

## deflate_stored (0x111910) — LIFTED + BUG-FIXED + COMMITTED. cdecl byte(int* s, int flush) level-0 store path.
## Analyst agent produced it (then stalled mid-stream); SELF-AUDIT caught a REAL BUG the (also-stalled, confused) reviewer missed:
##   BUG: the 2 inline flush_pending drains + final flush + 3 avail_out checks used the deflate_state base `s` directly for z_stream fields (next_out/avail_out/total_out/state), but those live in s->strm (the z_stream = *(int*)s). e.g. s+0xc=pending_buf_size NOT next_out; s+0x10=pending_out NOT avail_out. Original does MOV EDI,[ESI](=s->strm) then [EDI+0xc/0x10/0x14]. LCS byte-match HID it (opcode-normalized MOV reg,[base+off] matches regardless of base reg) -> 89.1% buggy.
##   FIX: introduced z=*(int*)s (s->strm); use z for next_out(z+0xc)/avail_out(z+0x10)/total_out(z+0x14)/state(*(int*)(z+0x1c)); final flush FUN_00110e70(z) not (int)strm. Pending/pending_out/pending_buf stay on `state`.
##   RESULT: VC71 89.1%(227/242) -> 90.8%(238/242). The +11 insns = exactly the z-stream derefs the original has. Build green, hazard clean. CORRECT + above-90 byte-match. Also restored fill_window(0x111770) @<esi> decl (ported still null) so deflate_stored's FUN_00111770(s) call passes state in ESI.
##   LESSON: NEEDS_RUNTIME / sub-90 caution is JUSTIFIED — LCS hides base-pointer confusion (z_stream vs deflate_state). Self-audit > stalled-agent here. §(new) base-pointer-confusion-hidden-by-LCS.
## NOTE: reviewer agents stalled twice today (API mid-stream); committed on thorough self-audit (which caught the bug) + objective VC71-jump confirmation.

## deflate_stored FIX COMPLETED (commit db3553c2, amended). Final VC71 = 91.7% (242/242 insns — exact count match), closure-check CLEAN.
## CRITICAL PROCESS LESSON (advisor): my first replace_all fixed only the SECOND drain — the two inline drains were NOT byte-identical (first had /* comments */, second didn't), so replace_all matched one. The partial fix left the FIRST drain on `s` base AND its avail-check reading uninitialized `z` -> WORSE than before, and I COMMITTED it (91.7%... no, 90.8% partial). The byte-match % CANNOT prove a base-fix is complete (LCS normalizes MOV reg,[base+off] across base regs; a surviving site = ~1 lost insn, invisible). The DEFINITIVE check is the advisor's grep: in deflate_stored body, `s+0x10`/`s+0x14`/`s+0x1c` MUST be 0 hits, `s+0xc` EXACTLY 1 (pending_buf_size); legit s offsets = 0x24/0x30/0x54/0x64/0x6c. After fixing BOTH drains: clean + 242/242.
## STANDING HAZARD (advisor): base confusion (z_stream=*(int*)deflate_state vs deflate_state) is a hazard for EVERY remaining zlib fn that inlines flush_pending/read_buf/get_byte: check_header 0x1128c0, gzread 0x1134e0, inflate_blocks 0x113a90. Cross-check the z_stream-vs-deflate_state base at each inline site BEFORE trusting any VC71 number. When fixing a repeated block with replace_all, VERIFY all occurrences were truly identical or the fix is partial.
## ROUND TALLY: 6 committed (read_buf 94.7, putShortMSB 87.8, flush_pending 88.9, deflate 91.6, callback-iterator 78.1, deflate_stored 91.7). fill_window deferred (stash@{0}, NEEDS_RUNTIME). Agents (analyst+reviewer) BOTH stalled today; self-audit+advisor caught a base bug the reviewer missed.

## ===== KEY TRIAGE FINDING (2026-06-30): many "remaining" real_math.obj fns are ALREADY LIFTED + PARKED =====
## Probed 0x110d40 thinking it was unlifted -> it has a pre-existing impl (real_math.c:4094) parked ported=false. The deactivation_allowlist.json shows MANY real_math.obj fns are parked: disasm-REVIEWED-CORRECT lifts held back by LOW VC71 (x87/idiom caps) awaiting STATE-SNAPSHOT equivalence that doesn't exist yet. So the "23 remaining" split into TWO classes:
## CLASS A — PARKED-CORRECT (impl exists, disasm-verified, needs snapshot+equiv to activate; NOT fresh lifts):
##   0x110d40 deflateSetDictionary 71.2% (impl @4094, clean strm/state base separation VERIFIED this session) — needs DEFLATE-STATE snapshot (zero-fill early-exits on state==0).
##   0x10a5e0 transition 75.3% x87-stack-chaining — needs CURVE-TABLE snapshot (early-exit on table-init *0x46e39c==0).
##   0x10a710 transition 52.4% (atan2 __asm CALL) — needs static-constant snapshot.
##   0x10ce10 vector_to_line_dist_sq3d — EXHAUSTIVELY analyzed (allowlist entry): FP-ORDER BRANCH-FLIP (x87 rounding straddles [0,1] clamp), NOT a clamp/arg bug (instruction-verified). Structural x87 cap. lift-score-improve op-order lever = uncertain payoff. Keep dormant.
##   deflateEnd ~85% — permuter candidate ([85,98] band) pending permuter pass.
##   (likely more: 0x18b010 70.7% x87, others "pre-gate baseline 2026-06-10")
## CLASS B — TRULY UNLIFTED (need fresh lifts, big/complex):
##   inflate_blocks 0x113a90 (~270 lines HUGE), longest_match 0x1114a0 (@eax hot loop), check_header 0x1128c0 (~150), gzread 0x1134e0, deflate_fast 0x111ba0 + deflate_slow 0x111ea0 (config funcs, BASE-CONFUSION HAZARD — inline flush_pending), gzopen-internal 0x113230, check_match 0x1116b0 (variadic debug), 0x110650/0x109f40/0x10f770/0x10fa30 (FP), low-addr stateful 0x1ada0/0x1aeb0/0x1b280/0x1b750.
## STRATEGY for next window: CLASS A is higher-leverage (already lifted, just needs verification) IF you can build the snapshots — DEFLATE-STATE snapshot (capture xemu during compression, or golden-harness src/halo/test_harness.c with a real deflate_state) unlocks 0x110d40; CURVE-TABLE snapshot unlocks 0x10a5e0/0x10a710. The recipe for FP-const snapshots: artifacts/snapshots/real_math_consts.json (per 0x10ce10 allowlist entry) + invoke unicorn_diff BY NAME not address. CLASS B = big fresh lifts, each needs dedicated fresh context + base-confusion cross-check (advisor) for the zlib ones.
## DO NOT re-probe CLASS A as if unlifted — check real_math.c for an existing impl + the allowlist reason FIRST (rtk rg '^.* FUN_<addr>' src/halo/math/real_math.c + rtk rg '<addr>' tools/audit/deactivation_allowlist.json).

## gzread (0x1134e0) COMMITTED (6fd2e442). cdecl int(int* gz, void* buf, int len). real_math.obj 149/171, 22 remain.
## Truly-unlifted (ported=null, NOT parked — 4 matches were callers gzgetc/gzgets/gzprintf). Single base (gz embeds z_stream at +0 -> all fields gz-relative, NO base-confusion possible). Restored check_header(0x1128c0) @<eax> decl (ported still null->routes to original) so gzread's FUN_001128c0((int)gz) passes gz in EAX; get_long FUN_001130d0 @<eax> likewise. Callees: inflate 1155e0, inflateReset 1153c0, crc32 110c10, get_long 1130d0, check_header 1128c0, csmemcpy, fread FUN_001db3f7, errno FUN_001db777 (int*).
## VC71 75.9% (192/211) — INVESTIGATED via compare_obj --show-diffs: gap is CODEGEN-STRUCTURE ONLY (prologue regalloc + branch-flavor idioms !=0->jne vs orig jbe + my goto-finalize consolidation vs orig scheduling). ALL logic blocks present (same next_out/crc32/get_long/check_header/inflateReset ops, reordered). NO missing path, NO wrong offset, single-base. Behaviorally faithful (block-by-block disasm trace + diff). 75.9% is a /lift-score-improve opportunity (restructure control-flow to match), NOT a correctness issue. Committed on self-audit+diff (reviewer agents stalling today; for deflate_stored self-audit OUTPERFORMED the stalled reviewer by catching a base bug).
## ROUND TOTAL: 7 committed (read_buf 94.7, putShortMSB 87.8, flush_pending 88.9, deflate 91.6, callback-iterator 78.1, deflate_stored 91.7, gzread 75.9). fill_window stash@{0} (NEEDS_RUNTIME). 0x110d40 parked (already-lifted, pending deflate snapshot).
## 22 REMAIN: CLASS A parked (need snapshots): 0x110d40 0x10a5e0 0x10a710 0x10ce10 0x18b010 deflateEnd. CLASS B unlifted: inflate_blocks 0x113a90(HUGE), longest_match 0x1114a0(@eax), check_header 0x1128c0(@eax ~150), deflate_fast 0x111ba0 + deflate_slow 0x111ea0 (BASE-HAZARD), gzopen-internal 0x113230, check_match 0x1116b0(variadic), FP 0x110650/0x109f40/0x10f770/0x10fa30, low-addr 0x1ada0/0x1aeb0/0x1b280/0x1b750.

## ===== DEFINITIVE TRIAGE of 22 unported real_math.obj (2026-06-30, name-accurate) =====
## 5 PARKED (impl EXISTS in source, disasm-correct, ported=false — work DONE, blocked on VERIFICATION):
##   0x109f40 FUN_00109f40 (matrix->euler, line 876), 0x10a5e0 FUN_0010a5e0 (transition), 0x10a710 transition_function_evaluate, 0x10ce10 vector_to_line_distance_squared3d, 0x110d40 FUN_00110d40 (deflateSetDictionary).
##   These need: FP-const snapshot equiv (artifacts/snapshots/real_math_consts.json EXISTS) BUT the asin/atan2 precision + asin-stub make equiv DIVERGE (tried 0x109f40: oracle vs lifted euler bytes differ, FPU sign flips — possible sign bug in parked impl OR asin-stub artifact; needs golden-harness or careful FP-order analysis, NOT activatable via plain equiv). 0x110d40 needs DEFLATE-STATE snapshot (not consts).
## 1 STASHED: fill_window 0x111770 (stash@{0}, NEEDS_RUNTIME, body-clean).
## 16 TRULY UNLIFTED (need fresh lifts, each its own context):
##   matrix_inverse 0x109a60 (PROVEN ceiling — SKIP per allowlist), 0x10a830 (@<ebx>), angular_accelerate_to_position 0x10f770 + accerate_to_position3d 0x10fa30 + 0x110650 (FP motion, trig caps), longest_match 0x1114a0 (@<eax> hot loop), check_match 0x1116b0 (variadic crt_fprintf debug), deflate_fast 0x111ba0 + deflate_slow 0x111ea0 (cdecl, BASE-CONFUSION HAZARD like deflate_stored — inline flush_pending; check z_stream-vs-state base!), check_header 0x1128c0 (@<eax>=gz ~150 inlined get_byte), gzopen-internal 0x113230 (@<eax>=mode), inflate_blocks 0x113a90 (~270 lines HUGE), low-addr stateful 0x1ada0/0x1aeb0/0x1b280/0x1b750 (datum/tag callees, crash-risk, runtime gate).
## CONCLUSION: NO clean win remains. The 5 parked need FP-equiv/golden infrastructure; the 16 unlifted are big/hazardous fresh lifts. matrix_inverse is a proven SKIP. Realistic max-activatable without new infra: the cdecl deflate_fast/slow (with base-confusion cross-check) + the gzio @reg fns (reviewer-1:1, will be sub-90/NEEDS_RUNTIME). Highest leverage = build a DEFLATE-STATE + a working FP-golden-harness to batch-activate the parked + state-dependent cluster.

## check_match (0x1116b0) COMMITTED. 95.0% VC71 (69/70, @reg prologue 1-insn gap). real_math.obj 150/171, 21 remain. ROUND=8 lifts.
## ABI @<eax>=length,@<ecx>=match,@<edx>=start,stack s. Debug match-verifier (csmemcmp window+match vs window+start; mismatch->crt_fprintf+assert; z_verbose>1->fputc dump). Single base (only s+0x30=window). Fixed 0x1db71f decl (was invalid "FID_conflict:FUN_001db71f" colon-name -> "int FUN_001db71f(int c,void*stream)" fputc). Inert in release (z_verbose-gated + assert only on real bug).

## ===== ROUND-END (8 lifts committed): real_math.obj 150/171, 21 remain =====
## Committed this round: read_buf 94.7, putShortMSB 87.8, flush_pending 88.9, deflate 91.6, callback-iterator 78.1, deflate_stored 91.7 (self-caught base bug), gzread 75.9 (diff-confirmed), check_match 95.0.
## gzopen-internal 0x113230 PREREQS (for next window): callee-decl fixes needed FIRST — FUN_001dbb00 (fdopen) is invalid "void(void)" -> set "void* FUN_001dbb00(int fd, const char* mode)"; verify debug_malloc + csstrlen 0x8df60 debug-arg variants (decompile shows 4-arg debug calls malloc(size,0,file,line)/strlen(s,0,file,line) but kb has 1-arg sigs — RECONCILE before calling); the gzip-header write is a 10-vararg FID_conflict__fwprintf (=crt_fprintf wide). @<eax>=mode. ~80 lines, file-state for equiv. Callees ready: csstrlen/csstrcpy/deflateInit2_ 112590/inflateInit2_ 1154a0/gz_destroy 112cd0/crc32 110c10/crt_fopen 1d9e59/check_header 1128c0(@eax decl set)/errno 1db777.
## REMAINING 21 = 5 parked (FP-precision/snapshot verification) + 1 stashed (fill_window) + 15 fresh-lift (matrix_inverse SKIP; longest_match 0x1114a0 @eax HOT-LOOP=compression-critical, do in FRESH context only; deflate_fast 0x111ba0/deflate_slow 0x111ea0 BASE-HAZARD; inflate_blocks 0x113a90 HUGE; gzopen-internal 0x113230 callee-decl-heavy; FP-motion 0x10f770/0x10fa30/0x110650 + 0x10a830 trig-cap; low-addr 0x1ada0/0x1aeb0/0x1b280/0x1b750 stateful-crash-risk).
## NO low-risk clean win remains in depleted context — check_match was the last. Each remaining needs FRESH context (big/intricate/callee-heavy) or verification INFRASTRUCTURE (FP-golden-harness, deflate-state snapshot). longest_match & deflate_fast/slow are compression-critical: a bug breaks ALL gzip — lift ONLY in fresh context with base-confusion cross-check + the §deflate_stored z-vs-s lesson.

## deflate_fast 0x111ba0 STRUCTURAL PREP (priority for FRESH window — do NOT attempt in depleted context):
## cdecl byte FUN_00111ba0(int* s, int flush). ESI=s, ~140 lines, COMPRESSION-CRITICAL (bug breaks all gzip). 3 compounding hazards:
##  (1) BASE-CONFUSION: the `if(iVar5!=0)` tail inline flush_pending uses iVar5=*param_1=s->strm — z_stream base. MUST use z=*(int*)s for next_out/avail_out/total_out/pending-state, NOT s. (Same class as deflate_stored bug. Apply advisor closure-grep: s+0x10/0x14/0x1c must be 0 hits.)
##  (2) MULTIPLE @reg CALL SITES (decompiler HIDES the reg args — recover each from disasm like deflate's putShortMSB): longest_match FUN_001114a0(@<eax>=s, +cur_match) [UNPORTED, set @<eax> decl first, routes to original]; check_match FUN_001116b0(@<eax>=length,@<ecx>=match,@<edx>=start,stack s) [PORTED this session].
##  (3) callees: fill_window 111770(@esi,decl set), _tr_flush_block 1177c0, _tr_tally FUN_00116d10, flush_pending 110e70, csmemcpy, fwprintf. _tr_tally 0x116d10 — verify ported+decl.
## state offsets (s int*): strm[0] window[0xc=0x30? NO: param_1[0xc]=window so s+0x30] ... NOTE decompile uses int-index param_1[N]: [0]strm [9]w_size [0xb]w_mask [0xc]window [0xe]prev [0xf]head [0x10]ins_h [0x13]hash_mask [0x14]hash_shift [0x15]block_start [0x16]match_length [0x19]strstart [0x1a]match_start [0x1b]lookahead [0x1e]max_lazy [0x20]strategy. (these are int-index; byte = *4). VERIFY against disasm.
## deflate_slow 0x111ea0 = sibling (lazy matching), same hazards + the lazy match_available state. Do after deflate_fast.
## RECOMMENDATION: in a fresh window, get full disasm of 0x111ba0, recover EVERY @reg call setup, write with z=*(int*)s base separation from the START, then VC71 (cdecl real gate) + advisor closure-grep + hazard. The regime catches base bugs (proven on deflate_stored).

## deflate_fast 0x111ba0 COMMITTED 90.4% VC71 (base-confusion AVOIDED: z=*(int*)s, closure-grep + compiled-output both verified z-base; advisor-validated). real_math.obj 151/171, ROUND=9 lifts.
## deflate_slow 0x111ea0 FULL STRUCTURAL PREP (mapped from disasm 0x111ea0-0x11225c; do in FRESH window with deflate_fast as template):
##  KEY: unlike deflate_fast/stored, deflate_slow CALLS flush_pending (FUN_00110e70(*(int*)s)) at ALL 3 FLUSH_BLOCK sites — NO inline drain -> NO base-confusion hazard. Still apply closure-grep as confirmation.
##  cdecl byte FUN(int*s, int flush). ESI=s. Lazy-match state offsets (BYTE): match_length 0x58, match_start 0x68, prev_length 0x70, prev_match 0x5c, match_available 0x60, max_lazy 0x78, strstart 0x64, lookahead 0x6c, block_start 0x54, strategy 0x80, w_size 0x24, window 0x30, head 0x3c, prev 0x38, ins_h 0x40, hash_mask 0x4c, hash_shift 0x50, w_mask 0x2c.
##  FLOW per iteration: fill_window(if lookahead<0x106; if <0x106&&flush==0 return 0; if ==0 goto FINAL); INSERT_STRING(if lookahead>=3) -> hash_head; prev_length=match_length, prev_match=match_start, match_length=2; IF (hash_head!=0 && prev_length<max_lazy && strstart-hash_head<=w_size-0x106){ if(strategy!=2) match_length=longest_match(s@eax,hash_head); if(match_length<=5 && (strategy==1 || (match_length==3 && strstart-match_start>0x1000))) match_length=2; }
##  THEN: if(prev_length>=3 && match_length<=prev_length){ MATCH-EMIT: max_insert=strstart+lookahead-3; check_match(prev_length@eax, prev_match@ecx, strstart-1@edx, s); _tr_tally(s, strstart-prev_match-1, prev_length-3)->bflush; lookahead+=1-prev_length; prev_length-=2; do{strstart++; if(strstart<=max_insert) INSERT_STRING; prev_length--;}while(prev_length!=0); match_available=0; match_length=2; strstart++; if(bflush){_tr_flush_block(s,buf,strstart-block_start,0); block_start=strstart; FUN_00110e70(*(int*)s); [FLUSH]print; if(*(int*)(*(int*)s+0x10)==0) return 0;} } 
##  else if(match_available){ LITERAL: if(z_verbose>1)print window[strstart-1]; _tr_tally(s,0,window[strstart-1])->bflush; if(bflush){_tr_flush_block; block_start=strstart; FUN_00110e70(*(int*)s); print;} strstart++; lookahead--; if(*(int*)(*(int*)s+0x10)==0) return 0; }
##  else { DEFER: match_available=1; strstart++; lookahead--; continue; }  (NO avail_out check on defer)
##  FINAL(lookahead==0, 0x112180): if(flush==0) assert("no flush?" 0x28d3bc); if(match_available){ emit last literal window[strstart-1] via _tr_tally(s,0,..); match_available=0; } _tr_flush_block(s,buf,strstart-block_start,flush==4); block_start=strstart; FUN_00110e70(*(int*)s); print; if(avail_out==0) return flush==4?2:0; return flush==4?3:1.
##  @reg calls SAME as deflate_fast: longest_match(s@eax,cur_match)[decl SET this session], check_match(len@eax,match@ecx,start@edx,s)[ported], _tr_tally FUN_00116d10(s,dist,len)[ported], _tr_flush_block 1177c0[ported], fill_window 111770@esi[set].
##  CRITICAL avail_out-check ASYMMETRY (verified vs disasm 0x11205e/0x1120ab/0x11216a): MATCH path bflush==0 -> loop (NO avail_out check); MATCH bflush!=0 -> FLUSH_BLOCK incl avail_out-return. LITERAL path ALWAYS checks avail_out after strstart++/lookahead--. DEFER path NO check. Get this wrong = wrong return timing.
## NEXT compression-critical (advisor): deflate_slow 0x111ea0 (prepped above) + longest_match 0x1114a0 (@eax hot loop, the actual match-finder — the LAST piece; decl already @<eax> set). Both fresh-window + full regime (closure-grep + VC71 + advisor) only.

## deflate_slow 0x111ea0 COMMITTED 91.9% VC71 (no base hazard=CALL flush_pending; operand-level+base verified; advisor-validated). real_math.obj 152/171, ROUND=10 lifts. DEFLATE COMPRESSION CLUSTER: deflate(110ed0)+deflate_stored(111910,L0)+deflate_fast(111ba0,L1-3)+deflate_slow(111ea0,L4-9) ALL DONE. Only shared longest_match remains.
## longest_match 0x1114a0 FULL DISASM MAP (do in FRESH window — most intricate, breaks ALL compression if wrong, NO functional gain since config funcs route to working original; @<eax>=s decl SET; self-audit is the gate, VC71 @reg-capped ~85-95% per advisor):
##  char* FUN(int s @<eax>, uint cur_match[EBP+8]). EBX=s, ESI=scan, EDI=match. Returns best_len (clamped to lookahead).
##  SETUP: chain_length[EBP-8]=max_chain(s+0x74); window=s+0x30; best_len[EBP-c]=prev_length(s+0x70); scan_init=ESI=window+strstart(s+0x64); nice_match[EBP-10]=s+0x88; limit[EBP-18]= (strstart > w_size(s+0x24)-0x106) ? strstart-w_size+0x106 : 0; prev_tab[EBP-20]=s+0x38; w_mask[EBP-1c]=s+0x2c; strend[EBP-14]=scan_init+0x102; scan_end1[EBP-1]=*(scan_init+best_len-1); scan_end[EBP-2]=*(scan_init+best_len).
##  ASSERTS: if(s+0x48(hash_bits?)<8) assert"Code too clever"@0x28d334; if(prev_length(s+0x70)>=good_match(s+0x84)) chain_length>>=2; if(lookahead(s+0x6c)<nice_match) nice_match=lookahead; if(strstart(s+0x64) > window_size(s+0x34)-0x106) assert"need lookahead"@0x28d324.
##  CHAIN LOOP do{ if(strstart(s+0x64) <= cur_match) assert"no future"@0x28d318; match=window(s+0x30)+cur_match;
##    QUICK REJECT: if(match[best_len]==scan_end && match[best_len-1]==scan_end1 && match[0]==scan_init[0] && match[1]==scan_init[1]) {
##      scan=scan_init+2; match=match+2; if(scan_init[2]!=match[0... actually after +2]) assert"match[2]?"@0x28d30c;  // checks 3rd byte
##      8-BYTE-UNROLLED: do{ 8x[ AL=*++scan; CL=*++match (INC ESI/EDI then [ESI+1]/[EDI+1] — careful: disasm does MOV AL,[ESI+1];MOV CL,[EDI+1];INC ESI;INC EDI;CMP;JNZ exit, x8) ]; }while(scan < strend[EBP-14]);  // exit label 0x111627
##      AFTER: assert(scan <= window+window_size(s+0x34)-1)"wild scan"@0x28d300; len = scan - strend + 0x102 (= scan - scan_init); ESI reset to scan_init=strend-0x102;
##      if(len > best_len){ if(len>=nice_match) {match_start(s+0x68)=cur_match; best_len=len; break;} match_start(s+0x68)=cur_match; best_len[EBP-c]=len; scan_end1=*(scan_init+len-1); scan_end=*(scan_init+len); }  // NOTE disasm: JLE 0x111676 skip; JGE nice -> 0x111696 (break, but match_start+best_len SET first at 0x111661/0x111664)
##    } // end quick-reject
##    cur_match = prev_tab[cur_match & w_mask] (u16); if(cur_match <= limit) break; chain_length--; }while(chain_length != 0);
##  CLAMP: best_len = min(best_len, lookahead(s+0x6c)); return best_len.
##  VERIFY against disasm 0x1114a0-0x1116a8: the 8-byte unroll INC-then-[+1] pattern (each step compares the byte AFTER the increment), the len computation (scan-strend+0x102), the scan_end reload offsets (scan_init+len-1 / scan_init+len), match_start set BEFORE the nice-match break. Pointer types: scan/match are char*; best_len/len signed int (JLE/JGE comparisons).
## ===== AFTER longest_match (advisor): compression cluster COMPLETE. Remaining tail is INFRASTRUCTURE-BLOCKED not lift-blocked: 5 parked (FP-golden-harness/deflate-snapshot), 4 low-addr STATEFUL non-math crash-risk (0x1ada0/0x1aeb0/0x1b280/0x1b750), trig-capped FP (0x10a830/0x10f770/0x10fa30/0x110650), inflate_blocks 0x113a90 (huge, needs inflate-state), gzopen-internal 0x113230 (CRT-decl-heavy), matrix_inverse 0x109a60 SKIP. CORRECT next action = BUILD snapshot/harness OR surface to user that tail needs it — NOT activate stateful/FP from depleted context. =====

## ===== MILESTONE: DEFLATE COMPRESSION CLUSTER COMPLETE (longest_match 0x1114a0 committed 85.5% @eax-cap) =====
## real_math.obj 153/171, 18 remain. ROUND TOTAL = 11 lifts. Full cluster: deflate(110ed0)+deflate_stored(111910)+deflate_fast(111ba0)+deflate_slow(111ea0)+longest_match(1114a0) + the I/O helpers (read_buf/putShortMSB/flush_pending/gzread/check_match/callback-iterator). zlib DEFLATE end-to-end now lifted.
## longest_match: @<eax>-cap 85.5%, self-audit gate. Advisor's CRITICAL check passed: the 3 setup comparisons (limit 0x1114cf JBE, chain-halve 0x111527 JC, nice-clamp 0x111533 JBE) operand-verified vs disasm — no </>= inversion (the silent-mis-tune trap, asserts+byte-match would NOT catch it). base-confusion absent (s-relative only, no s->strm deref).
## ===== ADVISOR DIRECTIVE (authoritative) — STOP inline-lifting here. The remaining 18 are INFRASTRUCTURE-BLOCKED, not lift-blocked: =====
##  5 PARKED (impl exists+disasm-correct, need verification infra): euler 0x109f40, transition 0x10a5e0/0x10a710, vector_to_line 0x10ce10, deflateSetDictionary 0x110d40 — need FP-GOLDEN-HARNESS (asin/atan2/cos precision: equiv diverges on stub) or DEFLATE-STATE snapshot (0x110d40).
##  1 STASHED: fill_window 0x111770 (NEEDS_RUNTIME).
##  4 LOW-ADDR STATEFUL non-math crash-risk (datum/tag callees, NOT pure math despite real_math.obj): 0x1ada0 0x1aeb0 0x1b280 0x1b750 — need runtime gate, do NOT blind-activate.
##  TRIG-CAPPED FP: 0x10a830(non-det random+cos) 0x10f770 0x10fa30 0x110650 — need FP-golden-harness.
##  inflate_blocks 0x113a90 (HUGE, needs inflate-state), gzopen-internal 0x113230 (CRT-decl-heavy: FUN_001dbb00 fdopen invalid + debug_malloc/strlen 4-arg variants), matrix_inverse 0x109a60 (PROVEN ceiling SKIP).
## CORRECT NEXT ACTION (advisor, repeated): BUILD the FP-golden-harness + a deflate/inflate-state snapshot, OR surface to user that the tail needs them. Do NOT activate stateful/FP from depleted context to satisfy the hook (it will never report satisfied on an infra-blocked set). The hook firing is not new info; the infra analysis is, and it's right.

## ===== INFRA-BUILD (user chose "build verification infra" for the parked cluster) — DIAGNOSIS + PLAN =====
## KEY FINDING: the 5 parked FP/zlib impls are CORRECT code; the blocker is the VERIFICATION HARNESS, not the lift.
##  - euler 0x109f40 (src real_math.c:876) VERIFIED disasm-faithful this session: pitch=-asin(matrix[7]) [FCHS present], yaw=atan2(inv_neg*m[8],inv_pos*m[9]), roll=atan2(inv_neg*m[4],inv_pos*m[1]), gimbal euler[0]=atan2(m[2],m[5]); const1@0x255e94=-1.0 const2@0x2533c8=1.0 eps@0x28c728. ALL match disasm.
##  - The earlier euler equiv divergence (oracle ST7=-0.46 vs lifted +0.46) is a HARNESS ARTIFACT not a code bug.
## ROOT CAUSE of equiv divergence on FP: asin FUN_001da0cc takes its arg on ST0 (x87: disasm does `FLD [mem]; CALL 0x1da0cc`), NOT a stack arg. The stub system (tools/equivalence/stubs.py get_stub_code) only models STACK-arg stubs (fabs = `FLD [ESP+4]; FABS; RET` = DD 44 24 04 D9 E1 C3). With no asin stub, FUN_001da0cc gets the DEFAULT stub (FLDZ/XOR EAX -> returns 0/garbage) in the ORACLE; meanwhile the CANDIDATE (clang build) calls clang's own asin() (the lifted C uses `asin((double)matrix[7])`), so oracle!=candidate -> large divergence that --float-tolerance can't absorb.
## INFRA FIX (do in FRESH window — delicate x87 encoding, doesn't fit existing stack-arg stub pattern):
##  In tools/equivalence/stubs.py get_stub_code, add ST0-input x87 stubs keyed by the asin/cos/atan2 callee names/addrs:
##   - asin (FUN_001da0cc, ST0 in/out): asin(x)=atan2(x,sqrt(1-x^2)). x87: FLD ST0(D9 C0); FMUL ST0,ST0(D8 C8); FLD1(D9 E8); FSUBRP ST1,ST0(DE E1)->1-x^2; FSQRT(D9 FA); FPATAN(D9 F3)->atan2(x,sqrt(1-x^2)); RET(C3) = b"\xD9\xC0\xD8\xC8\xD9\xE8\xDE\xE1\xD9\xFA\xD9\xF3\xC3". (CAUTION: the stub trampoline assumes stack args; ST0-input means NO arg pop — verify the trampoline preserves the incoming ST0 and the RET doesn't expect ESP cleanup. May need a new has_st0_input flag on the stub.)
##   - fcos (if a separate callee): FLD [ESP+4]; FCOS(D9 FF); RET — but euler's cos is OUR x87_fcos (compiles to FCOS both sides) so likely not needed.
##   - atan2/fpatan (2 stack args): FLD [ESP+4](y); FLD [ESP+8](x); FPATAN; RET — only if atan2 is a CALL (euler's is inline FPATAN, so not needed).
##  THEN: run `unicorn_diff.py FUN_00109f40 --allow-stubs --state-snapshot artifacts/snapshots/real_math_consts.json --float-tolerance 64 --mem-trace`. With a CORRECT asin stub, oracle asin ~= candidate clang-asin within ULPs -> tolerance absorbs -> verifies the euler logic. If pass -> activate (ported=true) euler + the sibling transitions 0x10a5e0/0x10a710 (same trig-cap, allowlist=disasm-reviewed-correct) + 0x10ce10.
## ALTERNATIVE infra (if the asin-stub ST0-ABI proves too fiddly): GOLDEN HARNESS (src/halo/test_harness.c) runs the REAL functions in-engine (real _CIasin) and compares lifted-C output with tolerance — but requires deploy+xemu and a NaN-boundary check (euler asin(matrix[7]>1.0)->NaN risk; memory: biped-aim euler NaN history).
## deflateSetDictionary 0x110d40 (parked, cdecl, disasm-correct, base-separation-verified) needs a DEFLATE-STATE snapshot (zero-fill early-exits on state==0) — separate from the FP-const snapshot.
## STATUS: infra DIAGNOSED + planned precisely; parked code CONFIRMED correct (euler). Implementing the x87 asin stub is the next concrete step (fresh window). real_math.obj 153/171.

## ===== INFRA BUILT + FIRST PARKED ACTIVATION (user chose "build infra") =====
## ONE-LINE INFRA FIX (committed f5a79fde): added "fun_001da0cc": "ciasin" to _CRT_MATH_ADDRS in tools/equivalence/stubs.py. The _CI_ONE_ARG intercept (stubs.py:1159, reads ST0->math.asin->ST0) ALREADY existed; only the address mapping was missing. My earlier "x87 asin stub machine-code" plan was UNNECESSARY — the harness handles _CI* math via Python math.* on ST0.
## EULER 0x109f40 ACTIVATED (ported=true, 154/171): equiv `unicorn_diff.py FUN_00109f40 --allow-stubs --state-snapshot artifacts/snapshots/real_math_consts.json --float-tolerance 64 --mem-trace --no-stub-arg-trace` => 100 passed / 0 failed, 82.3% cov, HIGH confidence. KEY recipe detail: --no-stub-arg-trace REQUIRED (oracle calls XBE _CIasin FUN_001da0cc, candidate calls clang asin = different symbol -> stub-arg call-seq differential false-fails; disable it, compare OUTPUT only).
## 0x10ce10 vector_to_line: RE-TESTED with working harness (--float-tolerance 256) = 27/100 pass, high conf -> CONFIRMS the structural FP-order branch-flip cap (allowlist analysis stands: x87 clamp-boundary straddle). STAYS PARKED (not activatable via equiv; would need bit-exact x87-order rewrite or golden-harness).
## REMAINING PARKED need DIFFERENT snapshots (asin fix doesn't unlock them):
##  - transitions 0x10a5e0/0x10a710: "table-init early-exit on *0x46e39c==0" -> need a CURVE-TABLE runtime snapshot (seed 0x46e39c!=0 + the table data; .bss runtime-init, needs xemu capture). 0x10a710 also uses asin (now intercepted) but the table early-exit makes equiv vacuous until the table is seeded.
##  - deflateSetDictionary 0x110d40: needs a DEFLATE-STATE snapshot (zero-fill early-exits on state==0).
## REUSABLE: the asin intercept + the "--no-stub-arg-trace for cross-build CRT-math" recipe now verifies ANY pure FP function using asin/acos/atan2/sin/cos/sqrt/log (the _CI_ONE_ARG/_CI_TWO_ARG intercepts). To map more _CI* addrs: add to _CRT_MATH_ADDRS (acos=0x1d94f0, asin=0x1da0cc; find sin/cos/atan2/sqrt/pow/fmod addrs as needed).
## ROUND TOTAL: 11 lifts + 1 infra-activation (euler) = 12 completed. real_math.obj 154/171, 17 remain (4 parked-need-snapshots[10a5e0/10a710/10ce10-cap/110d40], 1 stashed, 4 low-addr stateful, 3 trig-FP-motion[10a830/10f770/10fa30/110650], inflate_blocks, gzopen-internal, matrix_inverse SKIP).

## ===== 2nd + 3rd INFRA-ACTIVATIONS: transition_function_evaluate cluster =====
## REUSABLE TECHNIQUE (table-flag seeding): functions that early-exit on a table-init flag can be equiv-verified by SEEDING THE FLAG so the real logic is reached — the equiv only needs oracle+candidate to read the SAME seeded state (table contents need not be the real game values, just consistent). Steps: copy artifacts/snapshots/real_math_consts.json, add the flag region (e.g. d['regions']['0x0046e39c']='01000000'), run with --state-snapshot <flagged> --allow-stubs --no-stub-arg-trace --float-tolerance 64.
## transition_function_evaluate 0x10a710 ACTIVATED (ported=true, 155/171): equiv 100/100, coverage 46.8%->86.4% HIGH after seeding *0x46e39c=1 (without it: vacuous early-exit). committed.
## 0x10a5e0 (sibling) NOT activated: even with flag-seed + 300 seeds, 300/300 pass but coverage stuck 70.2% WEAK confidence (a SECOND gated branch in the uncovered 30%) — conservative: stays parked pending that gate's identification. disasm-reviewed-correct per allowlist, so likely correct, but weak-tier = don't activate without more coverage.
## ROUND TOTAL: 11 lifts + 3 infra-activations (euler 0x109f40, transition 0x10a710) wait =2 activations. = 13 functions completed. real_math.obj 155/171, 16 remain.
## INFRA STATE: asin intercept (stubs.py) + table-flag-seeding technique PROVEN. Remaining parked: 0x10a5e0 (weak, needs 2nd-gate seed), 0x10ce10 (structural clamp-flip cap), deflateSetDictionary 0x110d40 (needs a DEFLATE-STATE seed: status=0x2a + window/head/prev — bigger than a flag, like the transition but a full state struct). fill_window stashed. Unlifted tail: low-addr stateful 0x1ada0/0x1aeb0/0x1b280/0x1b750, trig-FP-motion 0x10a830/0x10f770/0x10fa30/0x110650, inflate_blocks 0x113a90, gzopen-internal 0x113230, matrix_inverse 0x109a60 SKIP.
## NEXT (fresh window): (1) deflateSetDictionary via a seeded deflate_state (status=0x2a@state+4, valid window/head/prev/w_size — arbitrary-consistent); (2) 0x10a5e0 2nd-gate identification; (3) the unlifted tail needs fresh-context lifts.

## ===== DEFLATE-STATE SNAPSHOT INFRA BUILT + deflateSetDictionary 0x110d40 ACTIVATED (real_math.obj 156/171) =====
## INFRA (user-requested "deflate-state snapshot"): tools/equivalence/make_deflate_snapshot.py — reusable generator that builds a SYNTHETIC, self-consistent deflate_state snapshot (page-isolated regions at 0x02000000+: strm/state/window/prev/head/dict). Seeds status=0x2a@state+4, w_size=0x400 (more=762), w_mask=0x3ff, hash_mask=0x7fff, hash_shift=5 + arg_overrides (param_1=strm, param_2=dict fixed; param_3=dictLength RANGE [64,1500] straddling the 762 truncation threshold -> covers BOTH no-trunc and trunc branches). JSON is gitignored (artifacts/snapshots/) + regenerable: `python3 tools/equivalence/make_deflate_snapshot.py -o artifacts/snapshots/deflate_state.json`.
## KEY HARNESS GOTCHA (cost the first run): deflateSetDictionary calls adler32 (FUN_00110a10, ported=true = same-TU LOCAL in candidate, EXTERNAL in per-fn oracle ref). The single-function candidate extraction leaves that local rel32 call dangling -> wild fetch crash eip=0x1ffffc (documented at unicorn_diff.py:1503). FIX = env BIPED_SIBLING_RESOLVE=1 + --real-callees: loads the delinked sibling body for BOTH sides (same bytes, adler runs real-on-both so strm+0x30 matches). REUSABLE for any zlib lift that calls a ported same-TU helper.
## VERIFICATION (combined, byte-exact vs MSVC oracle): main run (valid state, 50 seeds) = 50/50 pass, 95.9% coverage, mem-trace byte-exact across both branches, stub-arg differential clean (50 calls 0 mismatch); insurance run (status=0 via --status 0, 20 seeds) = 20/20 pass on the Z_STREAM_ERROR(-2) guard path. Together both return values + both branches + ~100% body verified. Confidence label = WEAK ONLY because monotonic_return forces WEAK regardless of coverage (deflateSetDictionary returns Z_OK on every valid path); the real evidence is mem-trace+coverage, which is strong. Advisor-confirmed activation (rule "WEAK->park" was guarding low-COVERAGE weak like 0x10a5e0 70.2%, not monotonic-return weak at 95.9%). Function is gameplay-dead (Halo inflates, never deflate-with-dictionary) so activation risk ~nil; equiv+disasm is the practical ceiling (runtime adds nothing).
## ACTIVATED: kb.json 0x110d40 ported false->true. Build GREEN ([100%] Built target halo, real_math.c.obj recompiled, raw-cast 411 baseline). Hazard --changed-only clean. real_math.obj 155->156/171.
## RECORDINGS NOTE (user asked re /mnt/g/dev/halo-memory-viewer/recordings): .halorec = HMRC datum-pool captures (object/actor/prop), NOT zlib deflate_state — they do NOT contain a deflateSetDictionary call, and deflate-with-dictionary is not a runtime path regardless. The in-game Derelict-MP capture WOULD seed FP-motion-family verification (physics state) once those are lifted — a real future asset for that cluster, not for deflate.
| FUN_000d8af0 | 0xd8af0 | hud_weapon.c | cdecl | 100.0% | committed | weapon-hud globals alloc |
| FUN_000d8b30 | 0xd8b30 | hud_weapon.c | cdecl | 100.0% | committed | weapon-hud globals reset |
| FUN_000d8b70 | 0xd8b70 | hud_weapon.c | cdecl(empty) | 100.0% | committed | no-op old-map dispose |
| FUN_000d8b80 | 0xd8b80 | hud_weapon.c | cdecl(empty) | 100.0% | committed | no-op dispose |
| FUN_000d8b90 | 0xd8b90 | hud_weapon.c | cdecl | 100.0% | committed | flags bit0 set/clear (folded-offset fix) |
| FUN_000d8bc0 | 0xd8bc0 | hud_weapon.c | @esi | 70.4% | committed | per-player accessor; body byte-match, @reg cap |
| FUN_000d8c30 | 0xd8c30 | hud_weapon.c | @esi | 72.4% | committed | 2nd-region accessor; body byte-match, @reg cap |
| FUN_000d8ca0 | 0xd8ca0 | hud_weapon.c | @eax+@esi | 82.8% | committed | tracked-weapon refresh; body byte-match, @reg cap |
| FUN_000d8fd0 | 0xd8fd0 | hud_weapon.c | cdecl | 100.0% | committed | path leaf-name (strrchr) |
| FUN_000d3080 | 0xd3080 | hud_draw.c | @eax+@ecx+@edx canary | 84.0% | committed | crosshair-overlay blit; reg-DEFINED cap, verified body, benign LOADW (&1 widen) |
| FUN_000d3200 | 0xd3200 | hud_draw.c | cdecl canary | 89.8% | committed | explicit-scale bitmap blit; scheduling-only diffs (permute-eligible) |

## Goal-lift run — 0/5 committed (queue_exhausted)

| function | addr | obj | vc71 | action | reason |
|---|---|---|---|---|---|
| FUN_0016f910 | 0x16f910 | rasterizer.obj | - | skipped | Callee FUN_0016f480 (0x16f480) takes implicit register args not annotated in kb.json: reads unaff_ESI (message string, NULL-asserted) and unaff_DI (profile index short). kb.json declares it as `void FUN_0016f480(void)` — missing the 1 stack arg (char flag), @esi, and @di. Both call sites in FUN_0016f910 load ESI with a string immediately before the CALL (MOV ESI,0x2a3d8c / MOV ESI,0x2a3d60) and keep the profile index live in DI. Lifting the caller requires first registering FUN_0016f480 in kb.json with correct @<reg> annotations (check-callee-regs skill). |
| FUN_0016fa40 (rasterizer_xbox_profile begin/close helper; kb decl: void FUN_0016fa40(int param1)) | 0x16fa40 | rasterizer.obj (true TU per __FILE__ string: c:\halo\SOURCE\rasterizer\xbox\rasterizer_xbox_profile.c) | - | skipped | Callee FUN_0016f480 (0x16f480) takes implicit register args NOT annotated in kb.json: decompile shows unaff_ESI (message string ptr — caller loads MOV ESI,0x2a3e18 / 0x2a3dec before each call) and unaff_DI (profile index, still live from caller), plus 1 stack bool arg. kb.json declares it as `void FUN_0016f480(void)` — wrong (no @<reg>, no stack arg). Calling it by name from C would drop ESI/DI args. kb entries for 0x16f480 AND 0x16fa40 itself need fixing before lift (0x16fa40's real param is a 16-bit short read via DI, kb says int — LOADW hazard; also 0x1ef8c0 D3DDevice_InsertCallback stdcall import not in kb). |
| FUN_0016eef0 | 0x16eef0 | rasterizer.obj | 71.1 | reverted_verify | structural_cap: Register-arg D3D wrapper ceiling + x87 FPU scheduling. 20+ reg-arg calls (D3DDevice_SetTextureStageState x12, SetRenderState_Simple x8, @ecx/@edx) compile to CALL to the file's Smart/Simple wrappers whereas the original inlines the ecx/edx setup before call 0x1e9410/0x1e9350 (documented ~65-80% reg-arg ceiling). Compounded by x87 scheduling of the two vertex-shader-constant blocks: the original keeps adiv/bdiv/dupA/dupB live on the x87 stack and fills the 6x vec4 matrix via fld st(3)/fxch, unreproducible from clean C array stores (~15pp permanent FPU-spill gap). Register-caching lever already recovered 66.8->71.1%. |
| FUN_00170c90 (rasterizer_screen_effect — evidence: assert __FILE__ "c:\halo\SOURCE\rasterizer\xbox\rasterizer_xbox_screen_effect.c" and error string "### ERROR rasterizer_screen_effect failed") | 0x170c90 | rasterizer.obj (kb.json objects[90], source "rasterizer/rasterizer.c") | 72.6 | reverted_verify | structural_cap: Register-arg caller ceiling: ~51 D3D @<ecx>/@<edx> call sites (SetTextureStageState, SetRenderState_Simple) compile as cdecl pushes under VC71 (CL.exe does not honor @<reg> annotations) whereas the delinked reference uses reg-arg mov edx/mov ecx sequences; the divergence at each site is systematic. regcall-elide made it worse (44.1%), confirming it is not elide-recoverable. Safe FCOMP operand-order flips (var-first load matching original fld/fcomp order) already applied, 71.7%->72.6%. Matches documented "@reg caller ~65-80% ceiling". |
| FUN_00172a30 (rasterizer_xbox_shadows.c:0x93 — shadow-pass begin / shadow generate setup) | 0x172a30 | rasterizer.obj (kb.json objects[90]) | 89.3 | reverted_review | NEEDS_RUNTIME: Target: FUN_00172a30 (rasterizer_xbox_shadows.c:0x93 shadow-pass begin / shadow-generate setup), 0x172a30, rasterizer.obj; impl in src/halo/rasterizer/rasterizer.c; thunk FUN_0017ccb0 in src/halo/effects/decals.c. Structural Match: 89.3% VC71/objdiff against a VALID registered per-function delinked reference (delinked/functions/00172a30.obj: 256 insns, FUN_00172a30 defined, FUN_00158140 extern). Real structural comparison. Band = <90%. Mismatch Classes: benign shape only (store-into-call-window scheduling, {0}/const materialization, REP MOVSD vs manual copy loop, register allocation). FPU projection core matches disasm exactly; no FPU-WARN. No unclassified control-flow/dataflow mismatch. Call Argument Audit: assert line-number pushes (0x9b-0x9e), cull 0x901, csmemset 0xf0, SetVertexShaderConstant(-0x44,vs_const,5) all match reference. FUN_00158140 5-arg cdecl proven by arg-count sweep (7 conclusive push=5; our site 0x172999 push=5); exact 5 constant VALUES inferred-consistent, not each byte-decoded. FUN_00158ae0(0) unchanged. Memory Offset / Global Side-effect Audit: 0x47e46c shadow param block (13-dword matrix @0x47e47c, RGB, radius), state resets, gated 0x5a5430 counter, and FPU matrix element offsets all verified. NOT fully decoded: pixel-shader block magic values at 0x5a5ac0/5a5ae0/5a5ae4/5a5b94/5a5b98 and fixed vs_const[8..19]. ABI Audit: regs=none, cdecl, no hazards. char-in-AL return discarded by void thunk. Clean. Confirmed: FPU projection math (inv_r, both matrix rows, negation, scaling) byte-correct vs disasm; cdecl ABI; FUN_00158140 arg count; assert/render gating structure; global store offsets. Inferred: exact FUN_00158140 constant argument values; pixel-shader-block magic constants; fixed vs_const constants; residual gap is compiler shape. Uncertain: no behavioral/runtime confirmation of the render side-effects; a subtle wrong constant in the PS block or vs_const would be a SILENT visual (shadow) regression invisible to VC71 % and static audit. Verdict Rationale: 89.3% falls in the fail-closed <90% band, which mandates golden/runtime behavior verification PLUS classified mismatches before commit. Mismatches are classified and benign and the static audit (ABI, call-arg count, FPU operand order, memory offsets) is clean with NO concrete bug found — so this is not a REJECT. But NO runtime/golden/equivalence evidence exists: the equivalence attempt returned not_applicable / missing_delinked_reference (harness searched whole-object delinked/rasterizer.obj.obj, ran 0 seeds — an infra/registration gap, not a passing run). This is a D3D-device-gated shadow-rendering function whose output is visual + hardware/global state, exactly the class where structural % is weak evidence and the box (equivalence via the per-function .obj, or an A/B trajectory / visual check) is the correct oracle. Structural evidence is too weak for auto-commit at this band without runtime confirmation. AUTOLIFT_REVIEW: NEEDS_RUNTIME |

## Goal-lift run 2026-07-05 — 7/47 committed (stop_on_fail_reached)

| function | addr | obj | vc71 | action | reason |
|---|---|---|---|---|---|
| FUN_0001cb30 | 0x1cb30 | - | - | skipped | Disassembly shows an implicit incoming EAX register argument (PUSH EAX at 0x1cb3b uses EAX without any prior definition in the function) forwarded as datum_get's 2nd parameter (int datum_handle). Ghidra's decompile silently dropped this argument, showing datum_get(DAT_006325a4) with only 1 of its 2 required args. kb.json's current decl 'void FUN_0001cb30(void)' is stale/wrong (real signature takes a stack param_1 at EBP+8 plus an implicit @eax register arg). Needs kb.json correction (add @eax annotation) before lifting; lifting directly from the decompile as-is would drop the datum_handle argument and call datum_get with garbage. |
| FUN_0001d530 | 0x1d530 | - | - | skipped | Hidden @eax input argument that Ghidra's decompiled signature omits. Both call sites in the sole caller (FUN_00020280 @ 0x20280, addrs 0x2030b and 0x203a4) execute `MOV EAX,EDI` immediately before `CALL 0x0001d530` without pushing EAX — EDI is the caller's object/datum handle param. Inside FUN_0001d530 that un-pushed EAX is consumed as the 2nd arg (datum_handle) to the first call, `datum_get(ECX=DAT_006325a4, EAX=<handle>)`, whose return value is discarded. Ghidra renders a bogus 1-arg call `datum_get(DAT_006325a4);` and never emits in_EAX/unaff_ tokens, so the mechanical pre-screen would miss it; only cross-checking both call sites' disassembly against the callee's asm revealed it. Existing kb.json decl (`void FUN_0001d530(void);`) is stale/wrong: real signature is 2 stack args (char param_1 @ EBP+8, int param_2 @ EBP+0xc, cdecl, `ADD ESP,0x8` cleanup at both call sites) PLUS the undocumented @eax handle. Do not lift until kb.json declares the @eax parameter (check-callee-regs / lift-arg-hazards doctrine). |
| actor_action_handle_vehicle_entry | 0x1dfa0 | actions.obj (also present in actors.obj) | - | skipped | Callee FUN_0001cb30 (0x1cb30) is called at BOTH call sites (0x1e0a1 and 0x1e1a6) with the actor_handle passed in EAX (`MOV EAX,EBX` immediately before `CALL`), plus one stack-pushed arg (an object/tag handle), returning bool in AL. kb.json only has `void FUN_0001cb30(void);` — no @eax annotation, wrong arity. Unaccounted register-arg callee per pre-screen rule (skip_reg_args). Needs kb.json fixed for FUN_0001cb30's real signature (@eax actor_handle + stack object handle → bool) first. |
| actor_action_handle_combat_selection | 0x1e8a0 | - | - | skipped | Callee FUN_000b5590 (called twice as FUN_000b5590(0x15)/FUN_000b5590(0x14)) decompiles as `void FUN_000b5590(void)` — Ghidra drops the visible stack argument. Disassembly: PUSH EBP/MOV EBP,ESP; CALL FUN_000a7460; MOV EBX,[EBP+8]; MOV EDI,EAX; CALL FUN_000b54e0 — the stack arg is loaded into EBX and never referenced again before the second CALL; it (and EAX from the first call, staged into EDI) are almost certainly forwarded via register — classic register-argument passing the decompiler can't see. None of the 11 non-intrinsic callees (FUN_00013070, FUN_00013ef0, FUN_00014620, FUN_0001d030, FUN_0001d350, FUN_000211f0, FUN_00031440, FUN_0003b320, FUN_0008d9f0, FUN_000b5590, FUN_000b5aa0) are registered in kb.json with documented @<reg> ABIs. Blocked until FUN_000b5590 (and its callees FUN_000a7460/FUN_000b54e0) are lifted/registered with correct register-arg annotations. |
| FUN_00111770 | 0x111770 | - | - | skipped | Decompile is riddled with unaff_ESI (register-passed struct pointer; kb.json decl confirms `int state @<esi>`). Body treats unaff_ESI as a large state struct (~30 int/short fields, indices 0x0-0x1b) doing zlib-deflate-style window/buffer sliding (memcpy shifts, hash update at unaff_ESI[0x10]/[0x13]/[0x14], csmemcpy, FUN_00117a80("more < 2") assert, FUN_00110a10 realloc-like helper). Pre-screen rule: any decompile with unaff_ registers is skipped. |
| FUN_0001cda0 | 0x1cda0 | - | - | skipped | Decompile reads `in_AL` (implicit register value Ghidra could not attribute to any named parameter) in three separate boolean checks (`in_AL != '\0'`), matching the unaff_/in_EAX/in_ECX register-arg pre-screen pattern. Likely hidden register-passed argument (flags/bool in AL) needing caller-disassembly confirmation before any lift. |
| FUN_001128c0 | 0x1128c0 | - | - | skipped | Decompile signature is `void FUN_001128c0(void)` with the real parameter surfaced only as `int *in_EAX` inside the body (register-arg, matches kb.json's already-declared `int gz @<eax>`). Pre-screen rule 1 (in_EAX present) → automatic skip_reg_args. |
| FUN_00113230 | 0x113230 | - | - | skipped | Decompile contains `in_EAX` (char *mode string pointer, used in the do-loop parsing 'r'/'w'/'a'/digit/'f'/'h' flags) — mandated pre-screen trigger. Partially reflected in kb.json's decl (`char *mode@<eax>`), but pre-screen protocol forces skip. Note: this is zlib's gz_open (literal "c:\halo\SOURCE\memory\zlib\gzio.c" and version string "1.1.3"), misclassified under real_math.obj in kb.json — grouping should be corrected before lifting. |
| actor_action_set_default_state | 0x1d7c0 | - | - | skipped | already implemented: src/halo/ai/actions.c (definition at line 1014, decl comment starts line 995; decl matches kb.json: char actor_action_set_default_state(int actor_handle, short state)) |
| actor_action_debug_color | 0x1d620 | - | - | skipped | Address falls within the CRT/intrinsics region 0x1d0000-0x1de000 per pre-screen rule, though the function itself calls no xboxkrnl imports. kb.json has a real name and decl `void actor_action_debug_color(void);`, decompile shows no register-arg smells and no __SEH wrapping — looks like a genuine game function (writes a debug color into DAT_006328e0..ec from a lookup table indexed by a datum's short field at +0x6c, then optionally invokes a function-pointer callback from a parallel vtable-like array). Flagged per the mechanical rule; recommend human sanity-check — CRT-region heuristic may be a false positive here. |
| actor_get_pursuit_location | 0x1d4f0 | - | - | skipped | Addr falls within the 0x1d0000-0x1de000 CRT-region window (skip_nt_import). NOTE: mechanical range match only — the decompiled body calls no xboxkrnl NT/kernel imports and is a plain datum-field accessor, not a CRT/intrinsic stub. Flagged in case the caller wants to override and proceed with a full lift. |
| actor_action_can_stop_conversing | 0x1cfa0 | - | - | skipped | already implemented: src/halo/ai/actions.c (line 747), full logic (datum_get/tag_block_get_element/flag checks), not a trivial wrapper. kb.json entry exists (addr 0x1cfa0, decl matches) but "ported": false — implementation exists in source but hasn't been toggled on/verified yet. |
| FUN_0001bcd0 | 0x1bcd0 | - | - | skipped | Callee FUN_0001b280 (0x1b280) is called with a hidden EAX register argument that Ghidra drops. Disasm at call site: `MOV EAX,EDI` (EDI=param_2) immediately precedes `CALL 0x0001b280` with no corresponding PUSH — FUN_0001b280 takes param_2 via @eax in addition to its 6 stack args (local_30, local_24, &local_18, 0, param_5+0xc, param_5+0x12). kb.json has only a placeholder decl for 0x1b280 (`void FUN_0001b280(void);`, no @eax annotation) — matches skip_reg_args. Lifting now would silently drop param_2 (check-callee-regs hazard). FUN_0001bba0 (0x1bba0) is also unported (placeholder void(void) decl) but its call site shows no hidden register args — 5 ordinary stack args matching Ghidra's decompile. |
| actor_action_handle_lost_contact | 0x1ef90 | - | - | skipped | Decompile contains unaff_ESI and unaff_EDI (register values not tracked as real params/locals) — relies on incoming register arguments Ghidra couldn't resolve. Also badly garbled: huge undefined stack array apppuStack_147f8[20515] from a _chkstk (FUN_001d90e0) call, dozens of undefined1**** pointer-cast locals, unreachable-block warnings — low-fidelity decompile not suitable for lifting as-is. |
| actor_action_handle_done_fleeing | 0x1f6e0 | - | - | skipped | already implemented: src/halo/ai/actions.c (line 1263 plate comment, function definition at line 1269: `char actor_action_handle_done_fleeing(int actor_handle)`) |
| actor_action_handle_combat_failure | 0x1f920 | - | - | skipped | already implemented: src/halo/ai/actions.c (function definition at line 1297, plate comment at line 1291) |
| actor_action_try_to_throw_grenade | 0x1fa60 | - | - | skipped | Callees FUN_00012f10, FUN_0001d180, FUN_000b5aa0, FUN_001a9ad0 all show param_count=0 in Ghidra signature (implicit register args/returns — e.g. FUN_0001d180(param_1) with result read back via extraout_AL; FUN_000b5aa0() called with no visible args but its return feeds a struct store) and none are registered in kb.json with @<reg> annotations. Blocked until those callees are added to kb.json. |
| actor_action_handle_berserk_transition | 0x20470 | - | - | skipped | already implemented: src/halo/ai/actions.c (function defined at line 1366, preceded by descriptive comment at line 1360) |
| actor_action_handle_grenade_throwing | 0x205a0 | - | - | skipped | already implemented: src/halo/ai/actions.c (line 1424, char actor_action_handle_grenade_throwing(int actor_handle)) |
| FUN_0001b750 | 0x1b750 | - | 90.8 | committed | permute |
| actor_action_handle_combat_targeting | 0x1dea0 | - | 93.6 | committed | pass1 |
| FUN_00021080 | 0x21080 | - | 100 | committed | pass1 |
| FUN_000210b0 | 0x210b0 | actions.obj | 100 | committed | pass1 |
| actor_action_handle_active_cover_seeking | 0x1e700 | - | 94.4 | committed | pass1 |
| actor_action_handle_combat_status | 0x1f770 | - | 72.6 | reverted_verify | structural_cap: MSVC register-allocation + branch-scheduling cap. VC71 spills the named `result` local (lives across the switch handler calls) into callee-saved EBX (`pushl %ebx`/`xorb %bl,%bl`/`movb %bl,%al`/`popl %ebx`), whereas the original keeps the disposition in EAX/AL flowing straight into the switch-tail `testb %al,%al; je handle_default; ret`. Remaining diffs are MSVC branch-polarity/logical-op scheduling (ref `jge/jle/jne` vs candidate `jl/jl/je`) from equivalent-but-opposite if/else lowering of the same short-circuit chains, compounded by kb-decl-mandated `int param2/param3` (byte-tested in the binary) forcing `(char)`-narrowing casts. Not a correctness bug: control flow and side-effect order verified faithful; reg-normalize does not recover the structural 72.6%. |
| FUN_0001bba0 | 0x1bba0 | actions.obj | 88.1 | reverted_review | NEEDS_RUNTIME: 88.1% LCS (108/110 insns, 2-insn multiset delta) in the sub-90 band, which mandates golden/runtime verification plus classified mismatches. Static body verified 1:1 against 0x1bba0 disassembly with no concrete defect (every call argument, memory offset, FCOMP polarity, 16-bit loop bound, EAX return matches) — not a REJECT. But the runtime leg is missing: only behavioral evidence is equiv_weak; leaf_cache records only {class: non_leaf} with no confidence/coverage tier. Non-leaf whose seat max-selection logic depends on scores from unported cdecl callee FUN_0001aeb0, which weak stubbed equivalence cannot exercise (multi-seat FCOMP-update branch is dark; only early-exit plausibly covered). Fail-closed: NEEDS_RUNTIME, not AUTO_ACCEPT. |
| FUN_0001beb0 | 0x1beb0 | actions.obj | 68.3 | reverted_verify | structural_cap: Residual gap is the MSVC EBX zero-register idiom: original materializes `xor ebx,ebx` once (push/pop ebx) and uses `cmp bl,al` / `cmp bl,mem` / `cmp bx,mem` for the many byte/word ==0 comparisons, while VC71 on the lifted C emits `test al,al` / `cmp $0,mem`. Cross-block register-allocation artifact not controllable from C source; cascades LCS misalignment. Instruction count matches exactly (102/103), equivalence 100/100 clean. Score improved 60.2→68.3 by fixing the block-layout inversion (the controllable part). |
| set_real_vector3d | 0x1d780 | - | 100 | committed | pass1 |
| point_to_line_distance3d | 0x1d7a0 | actions.obj | 100 | committed | pass1 |
| actor_action_allow_cover_seeking | 0x1ccc0 | - | 86.1 | reverted_review | NEEDS_RUNTIME: 86.1% VC71 (71/73 insns) against a valid per-function delinked reference. Single mismatch class: 2-insn reg-alloc/spill-reload compiler-shape delta, benign. Call args (datum_get, tag_get, game_time_get — all cdecl), all 9 actor offsets + 2 actr_tag float offsets, float constants (0.0f, 30.0f), int16 MOVSX truncation all verified 1:1; read-only, hazard scan clean. No detectable defect (not REJECT). But: state-dependent non-leaf; leaf_cache records only {"class":"non_leaf"} — no persisted confidence tier or coverage %; no golden/runtime evidence; "moderate" equivalence at best, inner cooldown/threshold branches likely dark under zero-fill. Sub-90 fail-closed policy: clean static audit does not clear AUTO_ACCEPT. Recommend golden/dual-oracle in-engine test or state-snapshot equivalence exercising the cooldown/threshold branches to promote. |
| actor_action_test_grenade | 0x1d180 | - | 76.7 | reverted_verify | structural_cap: MSVC cold-block outlining reorders the tail return blocks (reasons 6/8/7 emitted after 10/9, producing je/jl forward-jumps to out-of-line blocks vs inline jne/jge skip-overs), plus the original reuses the incoming parameter stack slot (EBP+0xa) as out_count scratch — a hostile optimization we correctly refuse (stack-reuse hazard) — shifting the local frame layout (-0x4 → -0x10 cascade). 162/164 instructions recovered; loss is ordering/layout, not correctness. Also minor MSVC load-folding/register-choice scheduling. |
| FUN_0001b8a0 | 0x1b8a0 | - | 75.1 | reverted_verify | structural_cap: Reg-arg-caller ceiling (~65-80%): two @<reg> callees force push-based VC71 codegen vs the reference's inline register setup — FUN_0001ada0 (@<eax>=actor_handle, @<esi>=*(actor+0x9c)) and FUN_0001b280 (@<ecx>=actor_handle, @<eax>=*(actor+0x9c)), both discovered from disasm (context metadata wrongly said has_reg_args=false). Compounded by x87 ST0-chaining on the two distance_squared3d compares (C stores/reloads ST0 where the original chains fcomp directly). VC71 reference is also stale/divergent from the current binary (ref uses mov edi,[ebp+8]/jg/jne vs current delinked obj and candidate mov ebx,[ebp+8]/jl/jp/je); --reg-normalize gave no gain (struct:75.1%), confirming a different reference compilation rather than a lift defect. Correctness independently confirmed by equivalence 100/100 seeds, 0 diverged, and instruction-by-instruction disasm verification. |
| actor_action_consider_grenade | 0x1fb80 | actions.obj (kb.json objects[15], source: ai/actions.c) | 88.8 | reverted_review | NEEDS_RUNTIME: 88.8% VC71, below the 90% band; plain cdecl (regs=none) so the LCS is informative, not a reg-defined-prologue ceiling. No FPU/LOADW/IMM warnings; permute stage did not run. Mismatch classes all benign compiler shape (short-circuit && vs nested-if; char vs undefined4 return; scratch-slot reuse; FCOMP idioms). All 8 CALLs resolved and cdecl-clean; named substitutions game_time_get/random_math_real verified against kb addrs; companion decl fix actor_action_test_grenade void(void)→char(int actor_handle) matches the 1-PUSH/AL-read call site. All offsets (0x5c/0x3e/0x180/0x182/0x1a0/0x1a4/0x6a0/0x6a4), const 0x253394, double-deref global *(char**)0x632574+0x3b4, and both FCOMP polarities verified; single side-effecting writes actor+0x6a4 and actor+0x6a0=1 faithful. ABI/hazard/buffer-alias clean. BLOCKING: only runtime evidence is a WEAK equivalence run (confidence=weak, coverage 32.6%, unique_returns=1 across 100 seeds) covering just the early-exit — enable flag @0x3b4 = 0 under zero-fill so `if(enable==0) return 0` fires immediately; the entire grenade-consideration core is dark. To clear: equivalence with actor/tag state-snapshot + non-zero enable flag, or golden/dual-oracle case. |
| actor_action_try_to_evade | 0x1fca0 | actions.obj (delinked/actions.obj contains FUN_0001fca0 per objdump -t) | 88 | reverted_review | NEEDS_RUNTIME: 88% (sub-90); acceptance path so far = permute, which cannot substitute for the <90% behavioral-verification requirement. Static body is a faithful 1:1 transcription: actr_tag&0x200000 branch swapped vs decompiler but semantically identical; 2D dot terms match term-for-term; impulse 1→7 / 0→6 / else assert@line 0xce3 + system_exit(-1) faithful; 37-byte code-size delta and 17 vs 21 relocs = reg-alloc/scheduling shape. No FPU/LOADW/IMM warnings. Call args all verified against 0x1fca0 disasm (incl. actor_move_try_evasion_direction 0x2ab40 7-arg call and actor_move_animation_impulse 0x2a7e0). trace_diffs=0 on covered path. LATENT NOTE: magnitude3d reads 3 floats but the C declares float scratch[2]/alignment_vec[2] — scratch[2] is a 1-float OOB read reproducing an MSVC stack-overlap quirk; only affects the v0==v1==0 zero-length gate or is discarded. ABI PASS (cdecl, regs=none); signature change void(void) → char(int actor_handle) correct. Equivalence FAILED 0/100 but the failure is a classified harness artifact, not a code bug: every seed dies at call[0] with `_datum_get arg[0]: oracle=0x00700300 candidate=0xcccccccc` — the GLOBAL actor_data pool pointer resolves via reloc in the oracle while the lifted .obj's global page was never seeded (0xCC guard fill). Coverage 13.1%, confidence weak, evade logic has zero positive behavioral coverage. Resolution: state-snapshot equivalence with live AI game state or golden/dual-oracle harness case; that would also settle the magnitude3d OOB edge. |

Committed: 7 (FUN_0001b750 90.8, actor_action_handle_combat_targeting 93.6, FUN_00021080 100, FUN_000210b0 100, actor_action_handle_active_cover_seeking 94.4, set_real_vector3d 100, point_to_line_distance3d 100)
Reverted structural_cap: 4 (0x1f770 72.6, 0x1beb0 68.3, 0x1d180 76.7, 0x1b8a0 75.1)
Reverted NEEDS_RUNTIME: 4 (0x1bba0 88.1, 0x1ccc0 86.1, 0x1fb80 88.8, 0x1fca0 88)
Skipped: 19 (8 reg-arg/callee-ABI blocks, 6 already implemented, 2 CRT-region range matches flagged as possible false positives, 1 garbled decompile, 2 in_EAX/in_AL pre-screen)

## Goal-lift run — 5/11 committed (queue_exhausted) — 2026-07-05

| function | addr | obj | vc71 | action | reason |
|---|---|---|---|---|---|
| actor_pursuit_find_nearby_actors | 0x20280 | delinked/actions.obj | - | skipped | Callee FUN_0001d530 (0x1d530) takes an implicit EAX register argument that Ghidra's decompiler silently drops, and it is NOT in kb.json. Disasm at both call sites in 0x20280 (0x20307-0x2030b and 0x2039a-0x203a4) shows the normal cdecl PUSH sequence for the two declared stack params, immediately followed by `MOV EAX,EDI` right before `CALL 0x1d530` — EDI holds this function's own param_1 (actor/object handle). Neither the decompile of FUN_0001d530 itself (`FUN_0001d530(char param_1, undefined4 param_2)`) nor the outer caller's decompiled call (`FUN_0001d530(param_2, *(int*)(iVar6+0x1c))`) shows this third EAX arg at all — it's a classic hidden @<reg> hazard per the check-callee-regs skill. Also note FUN_0001d530's own decompile calls `datum_get(DAT_006325a4)` with only one visible argument, another sign of a dropped/implicit arg inside that callee. Cannot safely lift actor_pursuit_find_nearby_actors until FUN_0001d530 (and its own datum_get anomaly) is properly attributed with an @eax annotation in kb.json. |
| actor_action_debug_color | 0x1d620 | actions.obj | 100 | committed | pass1 |
| actor_get_pursuit_location | 0x1d4f0 | - | 76.9 | reverted_verify | structural_cap: MSVC branch-scheduling idiom: reference hoists XOR EDX,EDX before a JNE to the pointer block and returns 0 via MOV EAX,EDX on the fall-through; clang emits a JE to a separate null block with its own XOR EAX,EAX and will not reproduce the block ordering from clean C. 19/20 insns match; single differing instruction is the conditional jump + swapped return blocks. Behavior verified equivalent (100/100 seeds). Ternary-form experiment produced identical 76.9%. |
| actors_searching_same_position | 0x20140 | - | 93.3 | reverted_review | infra_blocked: review_agent_returned_null |
| actor_action_handle_evasion | 0x20670 | - | 96.8 | committed | pass1 |
| FUN_00109a60 | 0x109a60 | real_math.obj | 69.7 | reverted_verify | structural_cap: Register-allocation/scheduling in a register-pressure-heavy nested cofactor loop: candidate spills loop counters local_c/local_10 to stack each iteration that the original kept in registers (128 vs 110 insns), compounded with int16 short arithmetic (testw/cmpw/movsx) throughout the index rotation. Matches documented 'MSVC register allocation/scheduling difference' (~87% ceiling) minus 'int16 movswl' (~15pp) structural patterns. Behavior proven by equivalence: 100/100 seeds, high confidence, 94.8% coverage. |
| FUN_0001bcd0 | 0x1bcd0 | - | 80.7 | reverted_verify | structural_cap: VC71 register-allocation + FP-spill scheduling ceiling. The byte-faithful form (three separate escaped floats local_18/14/10, matching the decompiler) recovers +3.4pp (80.7%->84.1%) by reproducing the original's store-then-reload of the distance-delta, but it is unbuildable under the actual clang build (-Werror,-Wuninitialized: clang treats the three floats as independent and does not see object_get_world_position writing them via &local_18) and is the forbidden contiguous-buffer hazard. The clang-safe float delta[3] array compiles clean and is 100/100 behaviorally equivalent, but lets VC71 keep delta on the FP stack instead of spilling. Residual divergence is pure VC71 codegen: 'within'(bVar1) allocated to BL byte vs the original spilling it as a dword into the param_5 home slot (ebp+0x18), param-home-slot scratch reuse, stack-slot layout differences, and 10 trailing function-alignment NOPs. No FPU/LOADW/IMM value bugs; equivalence 100/100. |
| actor_action_try_to_throw_grenade | 0x1fa60 | - | 93.4 | committed | pass1 |
| FUN_0001cb30 | 0x1cb30 | delinked/actions.obj (symbol FUN_0001cb30 present, offset 0x1290 in section 1) | 90.6 | committed | pass1 |
| FUN_0001d530 | 0x1d530 | actions.obj | 86.5 | committed | permute |
| actor_action_handle_vehicle_entry | 0x1dfa0 | actions.obj | 84.7 | reverted_verify | structural_cap: 84.7% is a structural ceiling, not a correctness bug. Evidence: no FPU-WARN/LOADW-WARN/IMM-WARN (all operand orders, load widths, and immediates match) and equivalence passed 100/100 seeds with 0 divergences. Residual gap sources: (1) the top early-gate paths use a shared `MOV AL,DL` tail with DL=0, which the decompiler faithfully renders as plain `return 0`; VC71 emits separate `XOR AL,AL` returns instead — the DL-through-tail idiom is not expressible from C without a dummy var; (2) the two loop counters (i over records, j over slots) are int16, so VC71 emits 32-bit movsx/inc/word-compare sequences (documented benign int16 reg-width ceiling); (3) Path A's distance temp stays in ST0 in the original (no memory store) whereas the C temp round-trips. Score is below the [85,98] permuter band, so permuter is ineligible; chasing the last points would churn a behaviorally-verified lift. |

## Goal-lift run — 1/2 committed (queue_exhausted)

| function | addr | obj | vc71 | action | reason |
|---|---|---|---|---|---|
| actor_pursuit_find_nearby_actors | 0x20280 | - | - | skipped | Callee FUN_0001d530 (0x1d530) takes an implicit @eax register argument that is NOT in kb.json. Confirmed via disassembly at both call sites in 0x20280 (0x203a2 and 0x309): "MOV EAX,EDI" immediately precedes "CALL 0x1d530" with EAX never pushed to the stack — the decompiler's pseudocode (FUN_0001d530(param_2, ...)) silently drops this third, register-passed argument. Callee-side disasm confirms the hazard: FUN_0001d530 immediately does "PUSH EAX" (0x1d53a) to forward the caller's EAX into datum_get(EAX, ...), i.e. EAX carries the actor/object datum handle. Per project convention (check-callee-regs), this is a classic hidden register-arg smuggling case and must not be lifted until FUN_0001d530 is registered in kb.json with an explicit @eax annotation. |
| actors_searching_same_position | 0x20140 | - | 93.3 | committed | pass1+equiv_weak [equivalence detail: Pipeline auto-ran zero-fill equivalence (no state snapshot; score >=90 so dedicated snapshot equivalence not required): 100/100 passed, 0 diverged, 0 stub-arg mismatches, but weak at 43.0% coverage — only the early-exit path (NULL search records from the +0x6c type-tag gate returning false) was exercised; the kind-0 distance branch, kind-1 index-equality branch, and kind-2 branch were not reached under zero-fill. Byte-match evidence (93.3% VC71) is the primary correctness signal here. — a 0-divergence pass on the live-state infection_swarm snapshot (populated datum tables, real actor handles) is accepted runtime behavioral evidence for the sub-90% band per the state-snapshot equivalence lane in CLAUDE.md] |

## Goal-lift run — 3/20 committed (queue_exhausted)

| function | addr | obj | vc71 | action | reason |
|---|---|---|---|---|---|
| FUN_0018bc60 | 0x18bc60 | scenario.obj | - | skipped | Target takes a HIDDEN @<eax> register argument (render-state pool datum index) that is missing from the kb.json decl and that Ghidra silently dropped (worse than in_EAX — the decompile shows datum_get(DAT_0050652c) with only ONE arg, but disasm 0x18bc6f pushes never-defined EAX as the datum_handle). Both original callers prove it: FUN_0018bf80 does `MOV EAX,EDI; CALL 0x18bc60` (0x18c06e) and `MOV EAX,ESI; CALL 0x18bc60` (0x18c091), loading the pool datum index into EAX immediately before each call. Lifting against the current 3-arg cdecl decl would read garbage EAX as the datum index. Lift requires: (1) new @<eax> annotation on the target decl in kb.json, (2) updating the two ALREADY-LIFTED call sites in src/halo/scenario/scenario.c (lines ~1304, ~1331). |
| global_structure_bsp_tag_index_get | 0x18b130 | scenario.obj | - | skipped | Target takes an implicit register argument: disasm shows PUSH ESI at 0x18b141 and 0x18b167 with ESI never written in the function — object handle arrives in @esi. It also returns float in ST(0) (FLD [0x2548fc] path + float10 return from 0x185a70). kb.json decl is `void global_structure_bsp_tag_index_get(void);` with NO @esi annotation and wrong return type — the Ghidra decompile silently drops the handle args (shows `object_get_and_verify_type()` with zero args). Lifting from this decompile without first fixing the kb signature (`float f(int object_handle@<esi>)`) would produce a broken ABI. Name is also suspect: body computes object screen diameter (bounding-sphere → render_frustum_sphere_diameter_in_pixels), not a BSP tag index. |
| FUN_0018b830 | 0x18b830 | scenario.obj | - | skipped | Decompile contains unaff_ESI: function receives an implicit struct/context pointer in ESI (used as unaff_ESI[0..0x10]) that is not annotated in kb.json (decl is "void FUN_0018b830(void);" with no @<reg>). Ghidra also shows a float param_1 passed on stack, so the true signature is @<esi> ctx + float — kb entry is wrong and must be corrected with an @esi annotation before lifting. |
| scenario_illumination_at_point | 0x18b930 | scenario.obj | - | skipped | Decompile contains in_EAX (hidden EAX register argument: output plane written through *in_EAX). Ghidra shows __fastcall(float*,float*,float*) plus in_EAX — 4 effective args with at least one undeclared register arg; kb.json decl is a placeholder "void scenario_illumination_at_point(void)" with no @<reg> annotations. Not liftable without ABI annotation work. |
| scenario_test_pvs | 0x18c3a0 | scenario.obj | - | skipped | already implemented: src/halo/scenario/scenario.c (function body at line 1174; kb.json has ported=false — implementation exists but is deactivated) |
| FUN_0018c5b0 | 0x18c5b0 | scenario.obj | - | skipped | Decompile contains unaff_BX (short) used as the gather-loop element counter — Ghidra lost the register init, so the body reads an 'unaffected' register. Additionally, callees FUN_00184de0 (render_location_visible) and FUN_00185a70 (render_frustum_sphere_diameter_in_pixels) are declared void(void) in kb.json but are clearly called with arguments in the decompile (float10 return from 185a70; iVar4+0x28 arg to 184de0) — implicit register/stack args not yet annotated, a second skip_reg_args trigger. No delinked reference exists either. |
| FUN_0018ca40 | 0x18ca40 | scenario.obj | - | skipped | Decompile contains unaff_EBX/unaff_ESI/unaff_EDI: Ghidra lost register dataflow for a float direction vector (EDI/ESI/EBX) that is defined in one branch (after FUN_00124730 succeeds) but appears undefined in the FUN_0010cc40 branch — the callee likely writes the vector via an out-buffer (&stack0xfffffff0) that the decompiler failed to map back to the registers. High-risk lift without manual disasm reconstruction. |
| FUN_0018cf10 | 0x18cf10 | scenario.obj | - | skipped | Decompile shows unaff_EBX, unaff_ESI, unaff_EDI — three implicit register arguments (EBX=sprite/flags struct, ESI=untransformed_origin, EDI=untransformed_direction) not annotated in kb.json (kb decl is void FUN_0018cf10(void), so the @<reg> args are unregistered). Fails pre-screen rule: register args present and not in kb.json. |
| scenario_object_name_index_from_string | 0x18d040 | scenario.obj | - | skipped | Decompile contains in_EAX (implicit register argument) — undeclared @eax ABI; kb decl is 'void scenario_object_name_index_from_string(void);' which contradicts the actual signature (in_EAX + float* param_1, short param_2, undefined4 param_3, int param_4, int param_5). Likely kb name/decl misattribution: body is float scaling math (reads flag byte at [EAX+0x10], multiplies *param_1 by short at [param_5+4], divides by _DAT_00506728), not a string-to-index lookup. |
| FUN_0018D140 | 0x18d140 | render_sprite.obj (binary evidence: __FILE__ string 'c:\halo\SOURCE\render\render_sprite.c'; task brief said scenario.obj — contradicted by evidence) | - | skipped | Decompile contains unaff_ESI — function takes an implicit ESI register argument (pointer to build_sprites group struct: reads +0x20 count, +0x10 flags, +0x4 vertex count, indexes 0x10-byte records at +0x24/+0x28/+0x30). kb.json decl is 'void FUN_0018D140(void);' with no @<reg> annotation, so ABI is unannotated. Also note: __FILE__ evidence says c:\halo\SOURCE\render\render_sprite.c ('a build_sprites_begin call can accomodate at most %d bitmaps', 'build_sprite failed to allocate dynamic vertices') — this is render_sprite.obj, NOT scenario.obj as the task brief claimed. |
| FUN_0018d490 | 0x18d490 | scenario.obj (per task; binary evidence says render_sprite.c — reclassification candidate) | - | skipped | Decompile contains in_EAX (basis output pointer, written extensively) and unaff_EBX (vector source pointer, read as unaff_EBX[0..2]) — implicit register arguments not annotated in kb.json. kb decl is "void FUN_0018d490(void);" with no @<reg> annotations, so the true ABI (thiscall ECX + stack args + EAX + EBX register args) is unrecorded. Would need kb.json @<reg> registration before lifting. |
| FUN_0018d6e0 (evidence name: build_sprite, c:\halo\SOURCE\render\render_sprite.c line ~0x1a2) | 0x18d6e0 | scenario.obj (kb objects[105]) — NOTE: __FILE__ evidence says render\render_sprite.c; this kb object already hosts render_sprite functions (neighbor 0x18d2c0 lifted into scenario.c) | - | skipped | Four callees receive implicit register args but their kb.json decls are void(void) placeholders with NO @<reg> annotations: FUN_0018cf10 (ESI=untransformed_origin, EDI=untransformed_direction + 3 stack), FUN_0018d490 (ECX=param_1 ctx, EAX=&basis_matrix, EBX=&buf + 3 stack), FUN_0018d040 (EAX=param_1 ctx, ECX=&param_8 scale + 4 stack), FUN_0018d140 (ESI=param_1 ctx + 1 stack). Calling them by current kb names drops the register args. These must be annotated/lifted first (all unported render_sprite neighbors). kb decl for the target itself is also a void(void) placeholder vs real 11-param cdecl. |
| scenario_trigger_volume_test_point | 0x18dfe0 | scenario.obj (per task) — evidence says triangle_strips.obj | - | skipped | Decompile contains `uint in_EAX` (returned in the empty-iterator fallthrough as `in_EAX & 0xffffff00`). Likely a benign Ghidra AL-only-bool-return artifact rather than a true register arg, but it trips the mechanical pre-screen. Bigger issue: KB NAME MISATTRIBUTION — the function body at 0x18dfe0 is NOT a scenario trigger-volume test. All three embedded asserts cite c:\halo\SOURCE\render\triangle_strips.c (lines 0x27/0x28/0x29/0x41) with strings "iterator", "vertices", "iterator->signature==_valid_strip_iterator_signature", "iterator->vertex_count>=0". It is a triangle-strip iterator next-triangle function (returns bool, emits 3 vertex indices into param_2, advances iterator with winding-parity flip at param_1+8). kb.json decl `void scenario_trigger_volume_test_point(void);` is wrong in name, object attribution (scenario.obj vs triangle_strips.obj), signature, and return type. Fix the KB entry before any lift. |
| scenario_debug_to_file | 0x18e1d0 | - | - | skipped | already implemented: src/halo/scenario/scenario.c (definition at line 1244 with full body and doc comment at line 1236; note kb.json has "ported": false — implementation exists in source but the patch is currently deactivated) |
| FUN_0018ff00 | 0x18ff00 | scenario.obj | - | skipped | Decompile contains in_EAX: function takes an implicit float* output pointer in EAX (writes a 3-float vector through it). Ghidra shows __fastcall(param_1, float *param_2, float param_3, float param_4) but the real ABI is EAX=output float[3], plus stack args (float* table, float scale, float magnitude). kb.json decl is a bare "void FUN_0018ff00(void);" with no @<reg> annotation — lifting requires adding @eax annotation first, so it fails the reg-args pre-screen. |
| FUN_0018b190 | 0x18b190 | scenario.obj | 87 | reverted_review | NEEDS_RUNTIME: The lift appears correct: ABI is clean (cdecl, regs=none), the hazard scan is clean, and every VC71 mismatch is classified as a benign compiler-shape or dead-code artifact. The most dangerous-looking item — 11 pushed args to object_get_node_matrices vs a 1-arg call — was chased to ground and resolved as behaviorally inert (independent 1-push caller at 0x14c92b, side-effect-free ported getter, return value used identically). The FPU-WARN is a base-fold with identical effective address and operand order, and the LOADW reads live only in the dead-arg setup. However, the acceptance policy is decisive here. Structural match is 87.0% (328/371), which is below the 90% floor. The `<90%` band explicitly requires golden/runtime behavior verification in addition to classified mismatches; absent that, the mandated verdict is NEEDS_RUNTIME. The only runtime evidence is an equivalence run that passed just 2/100 seeds with 98 INSN-LIMIT errors — the recursive walker spins forever on garbage sibling/child pointers, so only the object_handle==-1 early-exit path was exercised. The render body (LOD clamp, effect types 1/2, first-person-unit culling, debug-marker path, shadow pass, widget submission) has never been executed by any oracle. Combined with the non-conclusive callee-arity signal (check_arg_counts UNDER-DECLARED conclusive=0), there is no defect to reject on, but the structural evidence is too weak to auto-commit. A real-engine A/B trajectory check or a state-snapshot equivalence run that reaches the render body is required before commit. |
| FUN_0018b990 | 0x18b990 | scenario.obj | 44.9 | reverted_verify | below_65pct |
| FUN_0018C4D0 (no real name in kb; behavior suggests local_player_first_person_camera_check / "should render first-person" style predicate) | 0x18c4d0 | scenario.obj (kb.json objects[105], source "scenario/scenario.c") | 93 | committed | pass1 |
| FUN_0018d360 | 0x18d360 | scenario.obj (kb.json objects[105]) — NOTE: misattributed. Binary evidence (__FILE__ strings at both assert sites) places this in c:\halo\SOURCE\render\render_sprite.c. Sibling 0x18d2c0 (render_sprite builder init) is already lifted in src/halo/scenario/scenario.c under the same object, so keep the TU consistent. | 99.5 | committed | pass1 |
| FUN_0018dcf0 | 0x18dcf0 | scenario.obj | 86.4 | reverted_review | NEEDS_RUNTIME: Structural match is 86.4%, which falls in the <90% band. Policy for that band requires golden/runtime behavior verification plus classified mismatches; without golden/runtime verification the verdict floor is NEEDS_RUNTIME. No golden test, dual-oracle, or A/B trajectory run was performed (verify_payload skipped). The only behavioral check that ran — Unicorn equivalence — FAILED 0/100 with a deterministic call-sequence divergence at call index 2, which I could not conclusively attribute to a harness artifact. Compounding this: an unclassified FP-compare branch-polarity restructuring around the fade clamp ([67]/[80]) with a 118-vs-138 INSN-count divergence at RET, and FPU (fmod/FPREM1) hazard warnings present at scenario.c:566/:602 in the lifted body (guarded MSVC branches; shipping build uses x87_fmod, but the warnings are present, which blocks auto-accept). ABI, buffer, arg-count, and memory-offset evidence are all clean and the callees carry no implicit register args, so nothing here is a confirmed concrete bug that forces REJECT — the args that line up match and the near-dead negative-fade guard limits the branch-restructuring risk. But the lift cannot be auto-committed: the failed/inconclusive behavioral check and unclassified control-flow restructuring at 86.4% are exactly the conditions where the correct action is to demand runtime resolution. Recommend a dual-oracle harness at 0x18dcf0 (or A/B trajectory on a sprite-heavy scene) to (1) resolve the index-2 call-sequence divergence and (2) confirm the reordered fade-clamp branches are behavior-preserving, before this may be committed. |
| FUN_0018ef30 (suggested: scenario_debug_dump_status — prints scenario/bsp names + per-player positions; inferred from assert at scenario.c:183 and format strings) | 0x18ef30 | scenario.obj (kb.json objects[105], source "scenario/scenario.c") | 85.8 | reverted_review | NEEDS_RUNTIME: Structural Match 85.8% VC71 (104/108 insns) against valid per-function delinked ref delinked/functions/0018ef30.obj (registered in objdiff.json). No FPU-WARN, no LOADW-WARN. Build PASS, ABI audit PASS (regs=none), hazard scan clean for this lift. All 4 diffs classified benign (cold-path block outlining, register allocation, stack-cleanup coalescing, relocation-immediates-as-0). All 8 CALLs traced push-by-push including both risky MSVC deferred-vararg sites. Every global (0x326a08, 0x5064e4, 0x326a0c, 0x5aa6d4) and offset verified against disasm with correct widths. Buffer-alias hazard 5 correctly avoided. Read-only diagnostic print; no game-state mutation. But 85.8% is in the <90% band whose policy requires golden/runtime verification: the claimed "permute+equiv_weak" acceptance did NOT occur — pipeline shows permute skipped and equivalence skipped (missing_delinked_reference, seeds=0). No behavioral evidence on record; fail-closed. Clearing path: golden/dual-oracle harness capturing crt_fprintf output, or register the delinked ref for the equivalence lane and run unicorn_diff --allow-stubs; a permuter pass over the [85,89] band could also lift the match into a static-clearable range. |
| scenario_get_sound_environment | 0x18f600 | scenario.obj | 98.2 | committed | permute |
| FUN_0018fb20 | 0x18fb20 | scenario.obj | 46.7 | reverted_verify | below_65pct |
| FUN_0018fbc0 | 0x18fbc0 | scenario.obj | 82.8 | reverted_verify | structural_cap: 82.8% (265/271 insns; ~98% present, LCS-limited by ordering). Gap is entirely MSVC register-allocation/scheduling: the conditional tag-lookup idiom sky_tag=(ref!=-1)?tag_get():0 compiles in the reference with an ECX accumulator + movl %eax,%ecx;movl %ecx,%eax return-value round-trip (inlined-helper signature) at both resolve sites, plus FPU-compare folding (fcomps [const] vs flds;fcomps). The faithful fix (static helper called with sky_index and literal -1, which would reproduce the -1/else asymmetry) was attempted; VC71 refused to inline it (dropped to 69.5% with an added CALL), proving the pattern is unreachable from flattened C89 without banned inline asm. Matches the MSVC ternary/log scheduling cap. Behavior verified correct: no FPU operand-order or load-width warnings, no wrong constants/offsets/directions. |
| FUN_0018ffe0 (proposed: wind_update — assert string is c:\halo\SOURCE\scenario\wind.c:0x59 "wind_globals.initialized"; called from scenario_frame_update trampoline) | 0x18ffe0 | wind.obj (binary evidence: c:\halo\SOURCE\scenario\wind.c — NOT scenario.obj as the task header guessed; no obj registered in kb.json yet) | 86.3 | reverted_review | NEEDS_RUNTIME: 86.3% VC71 (182/189 insns) against delinked ref delinked/wind_FUN_0018ffe0.obj. All 7 mismatch insns classified benign compiler shape (count-publish register reuse at tail, loop-counter materialization/movsx scheduling). Full call-arg audit: all 9 callees cdecl, PUSH order and register loads match reference (scenario_get, display_assert 4-arg, system_exit(-1), tag_block_get_element stride 0xf0, tag_get('wind'), random_math_get_local_seed_address, random_range(seed,0,2), vector_to_angles, angles_to_vector). Memory offsets verified 1:1 (record stride 0x20; t@+0x4, pitch@+0x8, yaw@+0xc, velocity@+0x10, direction@+0x14, valid@+0x0; globals 0x5064c8 tick, 0x5060c4 int16 count, 0x5057c0 init flag, 0x5060c8 array). ABI clean, regs=none. BLOCKING at this band: FPU clamp constants and the +/-0.01 branch selection are structurally indistinguishable in the delinked reference (every clamp bound loads relocated ds:0x0), so VC71 LCS cannot detect a swapped clamp bound or flipped sign selection; equivalence run is confidence=weak at only 8.4% coverage (assert/skeleton path only) — the entire random-walk/lerp/vector body is dark. No concrete bug found and ABI fully proven, so not a REJECT — but structural evidence is too weak to commit without runtime/golden verification of the FPU body. |

## Skip-queue work session 2026-07-04 (post-run, no agents)

| function | addr | score | action |
|---|---|---|---|
| FUN_0018fb20 | 0x18fb20 | 73.3 (was 46.7) | committed faca1442 — NaN branch-polarity fix (delta<neg_max), equiv 100/100 high |
| wind_update | 0x18ffe0 | 86.3 | committed aa763e5d — new TU wind.c; synthetic-snapshot equiv 3x30/30 HIGH |
| scenario_test_pvs | 0x18c3a0 | 83.8 | ACTIVATED 245775cd — WRONG-CALLEE FIX: flush = FUN_0016b240 not FUN_0017cbf0 (reloc-verified); equiv 30/30 @100% cov |
| scenario_test_pas | 0x18c460 | 97.0 | LIVE BUG FIXED same commit — brackets are FUN_00172520/FUN_00172720, not FUN_0017cca0/FUN_0017cd10 |
| scenario_debug_to_file | 0x18e1d0 | 83.0 | ACTIVATED 2ed2bfff — return type is char (MOV AL,1), was int (garbage upper EAX); equiv 110/110 |
| FUN_0018ff00 | 0x18ff00 | 72.7 | committed 85eeaded — wind noise sampler @eax/@edx, moved to wind.obj; equiv 100/100 BYTE-EXACT after forcing MSVC x87 single-rounding via volatile spills |
| FUN_0018b130 | 0x18b130 | 94.3 | committed e95cca53 — object screen diameter @esi; kb name global_structure_bsp_tag_index_get was WRONG, reverted to FUN_ |
| FUN_0018bc60 | 0x18bc60 | - | @<eax> render_state_index annotated + both dormant bf80 call sites fixed (c810b59d); bc60 lift still todo |
| FUN_0018bf80 | 0x18bf80 | 79.1 | still dormant; refresh path equiv 20/20; evict/alloc need sequenced stub returns or live snapshot |

Harness: identity-relocation of snapshot-covered DAT_ symbols (2976262a) — fixes oracle slot-vs-table asymmetry for indexed tables.
Remaining skip queue: FUN_0018b830 (@esi+float), scenario_illumination_at_point 0x18b930 (in_EAX plane out), FUN_0018c5b0 (unaff_BX + callee decls), FUN_0018ca40 (EBX/ESI/EDI out-buf artifact), FUN_0018cf10 (decl in parked dcf0 v2 patch), scenario_object_name_index_from_string 0x18d040 (in_EAX + misattrib), FUN_0018D140/FUN_0018d490/FUN_0018d6e0 (render_sprite cluster), FUN_0018bc60 lift (large render_objects lighting fn; siblings FUN_0018b610/b6b0/b780 need check-callee-regs first), FUN_0018bf80 activation (blocked on bc60).

## Retry session 2026-07-04 (late) — fbc0 + dfe0 CLOSED
| Function | VC71 | Evidence | Commit |
|---|---|---|---|
| FUN_0018fbc0 (atmospheric fog window update) | 95.8% (was 82.8 reverted) | reloc audit clean; equiv 3 synthetic paths 90/90 (indoor-smooth 61.4% cov high, outdoor-snap 41.5% via --real-callees/--no-stub-arg-trace [oracle-stub sibling asymmetry], no-sky 25.5%); levers: accumulator anti-tail-merge (+3.5pp), literal float stores; jp/jne 1-insn NaN-fidelity price kept; also fixed stale kb decls (fbc0 void(void)->real 4-arg, interpolate_scalar 0xb6e60 void(void)->(float*,float,float)) and replaced render.c:134 raw cast | 97376bbb |
| triangle_strip_iterator_next 0x18dfe0 (kb name scenario_trigger_volume_test_point was a MISATTRIBUTION; asserts prove render\triangle_strips.c) | 94.6% | reloc audit clean (4 assert clusters); equiv 4 synthetic branch paths 80/80 (union = all non-assert paths); AL-only char return; 5 diffs = pure scheduling | 64eddf7f |
Skills updated (see .claude/skills commit): lift-synthetic-equivalence (new), lift-silent-bugs Check 0 (reloc audit), lift-score-improve 3b/3c.

## Goal-lift run 2026-07-07 — 2/20 committed (stop_on_fail_reached)

| function | addr | obj | vc71 | action | reason |
|---|---|---|---|---|---|
| plane_negate | 0x994d0 | geometry.obj | - | skipped | already implemented: /mnt/g/dev/halo-clean-main/src/halo/math/geometry.c:9 (void plane_negate(float *plane_in, float *plane_out)) |
| FUN_00146be0 | 0x146be0 | bsp3d.obj | - | skipped | Decompile contains unaff_EBX and unaff_EDI (combined via CONCAT44 into uVar10, passed as a bogus 2nd arg to FUN_00145a60). This trips the mechanical skip_reg_args gate. NOTE FOR ORCHESTRATOR: this is very likely a SPURIOUS Ghidra artifact, not a genuine register-arg dependency. FUN_00145a60 is already in kb.json as `char breakable_surface_extant(short breakable_surface_index)` — a single-arg cdecl. The unaff CONCAT44 is a phantom extra argument Ghidra invented for a call that actually takes only the 16-bit index (iVar5). FUN_00146be0 itself takes only stack param_1 (void *damage_params, per kb decl). All 4 FUN_ callees are in kb.json with proper cdecl decls and none carry @reg. So this may in fact be liftable — the agent would just write breakable_surface_extant((short)iVar5). Recommend manual re-review rather than hard skip. |
| convex_hull2d_perimeter | 0x106390 | geometry.obj | 92.5 | committed | mechanical gate: 92.5% clean (pass1) |
| convex_hull2d_test_vector | 0x1063f0 | geometry.obj | 65.4 | parked | structural_cap[agent-judgment]: x87 FPU-stack register-scheduling ceiling: the Liang-Barsky min/max select keeps t/tmin/tmax live on the x87 stack in the original (fld/fst/fxch/paired fstp conditional juggling across the branch), which clean C89 cannot express — it emits memory store/reload instead. Compounded by the int16_t loop counter forcing movswl widening. Instruction count matches (109/108) and no FPU-WARN, so the gap is pure scheduling, not a logic defect. |
| convex_polygon2d_verify | 0x106900 | geometry.obj | 92.8 | committed | mechanical gate: 92.8% clean (pass1+redelink) |
| convex_polygon3d_clip_to_plane | 0x106960 | geometry.obj | 74.3 | parked | structural_cap[agent-judgment]: FPU-heavy Sutherland-Hodgman clip: residual VC71 gap is x87 operand-order and register-allocation/scheduling variance (FPU-WARN shows %edx/%ecx/%esi allocator differences). Candidate/reference insn counts are near-equal (401 vs 398), so logic is faithfully reproduced. The near-identical 2D sibling convex_polygon2d_clip_to_plane is an accepted lift capped at 74.1% — same family, same ceiling. |
| FUN_00106dc0 | 0x106dc0 | geometry.obj | 76.9 | parked | structural_cap[agent-judgment]: x87 scheduling / register-allocation ceiling (documented ~73-82% band): MSVC interleaves callee-saved register pushes (ebx/edi) and the counter init into the FPU computation block, keeps edgeA entirely on the x87 stack across the cross product, and reuses the incoming param stack slot [ebp+0xc] for last=n-1 (mine gets a fresh slot, shifting ax/di vs bx/si allocation). Instruction multiset matches (144 vs 142) and cross order + epsilon were hand-verified, so the residual gap is scheduling, not correctness. classify_cap.py returned inconclusive; this is my judgment. |
| FUN_00106f50 | 0x106f50 | geometry.obj | 79.5 | parked | structural_cap[agent-judgment]: x87 stack-order scheduling ceiling: 477/479 instructions match the reference by count (structurally near-identical, no missing logic/wrong offset/wrong branch); every FPU-WARN is a pure arithmetically-identical x87 load/multiply reorder in the pass-3 projection dot product (flds (%ecx) vs flds 0x4(%ecx); fmul %st(4) vs %st(3)) that MSVC's scheduler chooses differently and C89 cannot force without banned inline asm. Same-file FPU neighbors are also capped (convex_polygon2d_clip_to_plane 74.1%, convex_hull2d_perimeter 92.5%). |

## Goal-lift run 2026-07-07 — 4/20 committed (queue_exhausted)

| function | addr | obj | vc71 | action | reason |
|---|---|---|---|---|---|
| bsp3d_find_leaf | 0x146db0 | bsp3d.obj | 98 | committed | mechanical gate: 98% clean (pass1) |
| FUN_00146d40 | 0x146d40 | bsp3d.obj | 94 | committed | mechanical gate: 94% clean (redelink) |
| bsp3d_clip_line_to_leaves | 0x146e30 | bsp3d.obj | 94 | committed | mechanical gate: 94% clean (redelink) |
| FUN_001470b0 | 0x1470b0 | bsp3d.obj | 94 | committed | mechanical gate: 94% clean (redelink) |
| FUN_00146be0 | 0x146be0 | bsp3d.obj | 88.4 | parked | NEEDS_RUNTIME: Target: FUN_00146be0 (0x146be0, bsp3d.obj) — breakable_surfaces_area_of_effect_damage, src/halo/physics/bsp3d.c. Structural match 88.4% (sub-90% band). Structural Match: 88.4% VC71. Per policy the <90% band requires golden/runtime behavioral verification of the actual body plus classified mismatches; without it the verdict is NEEDS_RUNTIME. Mismatch Classes: I did not isolate individual mismatch instructions, but the ~11.6% gap is consistent with reg-alloc/scheduling/epilogue shape — no unclassified control-flow or dataflow divergence was found. Not a defect signal on its own. This alone would need the sub-90 band's runtime evidence regardless. Call Argument Audit (full 1:1 vs disasm, all cdecl, ABI regs=none): scenario_get(); tag_get(0x6a707421, *(int*)damage_params) [reverse-push verified]; error(2, str@0x29c9b8, effect_radius promoted to double via FSTP qword); tag_block_get_element(block, surface_index, 0x30); breakable_surface_extant(i); breakable_surface_get(i); breakable_surfaces_get_bsp_surface_data(); FUN_00145ad0(i, damage_params, *(int*)(surf+0x10)). All arg orders and counts match the disassembly and generated decl.h signatures. Memory Offset / Global Side-effect Audit: enabled flag *breakable_surface_globals read as byte (MOV AL,[EDX]) matches HDATA char*; guard floats +0x1d4/+0x1d8; effect_radius jpt+0x4; error threshold 4.0f (0x2533d8); count/block at scenario+0x16c re-read each iteration; surf fields +0/+4/+8 (pos), +0xc (radius), +0x10 (spawn arg); damage_params +0x28/+0x2c/+0x30 (pos). Side effects: *(uint32_t*)surf_health=0, and BSP bitfield word_ptr &= ~(1<<(idx&0x1f)) at bsp_data+(idx>>5)*4 (SAR = signed). All verified. Three FPU polarities decoded correct: two guard !=0.0f (TEST AH,0x44 JP/JNP), effect_radius>4.0f error gate (TEST AH,0x41 JNZ), and dist² <= (surf_radius+effect_radius)² via FCOMPP(thr²,dist²)/TEST AH,0x1/JNZ decoded stack-slot by stack-slot. Dual-index preserve-shape is FAITHFUL: raw int EBX drives breakable_surface_extant/get + FUN_00145ad0, sign-extended short EDI (MOVSX EDI,BX) drives tag_block_get_element index and the bitfield — the source's i (int) vs surface_index=(short)i models this exactly. ABI Audit: audit_reg_abi.py --target 0x146be0 → regs=none, no register-ABI hazards. Hazard scan (check_lift_hazards.py --changed-only) exit 0, no findings. kb.json change is minimal (adds "ported": true; cdecl decl unchanged). Confirmed: full static 1:1 body fidelity, no concrete bug; ABI clean; hazard clean; all call-site args, offsets, side effects, and FPU polarities correct. Inferred: the ~11.6% VC71 gap is benign compiler shape. Uncertain: BODY runtime behavior is unverified. The equivalence that actually ran is zero-fill only, coverage 16.1% (weak): with char* breakable_surface_globals zero-filled, all 100 seeds hit the enabled-flag guard and early-exit. The stub-arg differential's 200 calls cover only scenario_get + tag_get (both BEFORE the guard) — the AoE surface loop, distance test, bitfield clear, and FUN_00145ad0 spawn were NEVER exercised. The acceptance path's "live-state infection_swarm snapshot = accepted runtime evidence" lane never executed: artifacts/snapshots/infection_swarm.json is absent (only d1f40_synthetic.json present). A 100/100 pass on a guard-only path is vacuous for the body. Verdict Rationale: This is not a REJECT — I found no concrete likely bug, ABI evidence is present, FPU ordering/polarities are verified, and control flow is fully classified. But 88.4% is squarely in the <90% band, whose policy mandates golden/runtime verification of behavior, and the only runtime that ran covered 16.1% (the guard/early-exit), leaving the entire damage-application body runtime-unverified. This is the same shape as the consider_grenade 88.8% precedent (static-verified faithful, no body-covering runtime → NEEDS_RUNTIME), and distinct from 0x1d530 / allow_cover_seeking, which cleared only because a PASSING equivalence on a real/live snapshot genuinely exercised the body. To clear to AUTO_ACCEPT: run equivalence on a live-state snapshot where the scenario has breakable surfaces and damage_params is populated, so the AoE loop, distance test, bitfield update, and effect spawn run at 0-divergence. |

## Round tally: 4/20 functions committed (bsp3d cluster 98%+94%+94%+94%); queue exhausted on first sub-90% target (FUN_00146be0, NEEDS_RUNTIME). Session hit policy band correctly: one structural-cap/mis-skipped target auto-parked pending runtime verification. bsp3d.obj now complete for >=90% VC71 tier; remaining work = live-state verification via infection_swarm or equivalent snapshot.
