#!/usr/bin/env python3
"""
vc71_regression.py — Track VC71 match scores and detect regressions.

STATUS: Active.  Generates and updates tools/verify/vc71_scores.json which is
committed to the repo.  The scores file is consumed by tools/analysis/frontier.py,
tools/llm_auto_lift.py (liftability scoring), and tools/equivalence/batch_equivalence.py
(priority queue).  No auto-callers; run manually after bulk lifts.

Manages tools/verify/vc71_scores.json (committed to repo), which records the
expected minimum VC71 match percentage for each ported function. Used to catch
edits that silently degrade byte-match quality.

Commands:
    update --source src/halo/game/game.c [...]
        Run vc71_verify on the given source file(s), update the stored
        floor scores. Raises stored score when a function improves; never
        lowers it automatically (use --force to lower).

    check [--source src/...] [--threshold N]
        Run vc71_verify and compare against stored floors.
        Exits 1 if any function dropped more than --threshold pp (default 2).
        Limits to specific files when --source is given.

    show
        Print the current baseline in a human-readable table.

    populate
        Re-derive scores for every ported function in kb.json by scanning
        all relevant source files (slow, but useful for initial population
        or after bulk changes). Writes new floors for any function not yet
        in the baseline.
"""

import argparse
import bisect
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
# Floored regression tripwire (committed; consumed by frontier.py, llm_auto_lift.py,
# batch_equivalence.py and CI's `check`).  Only raised on improvement / lowered
# deliberately with --force.
BASELINE_PATH = Path(__file__).parent / "vc71_scores.json"
# Honest current scores (bidirectional, gated on reference validity).  Written by
# `populate`; preferred by the dashboard so it reflects present truth, not a
# high-water mark.  Regenerated each run — not a committed baseline.
CURRENT_PATH = Path(__file__).parent / "vc71_current.json"
# Functions whose delinked reference failed validation (truncated/absent) and were
# therefore NOT scored.  These need re-delinking before their score is meaningful.
VALIDITY_PATH = REPO_ROOT / "artifacts" / "audit" / "reference_validity.json"
# Per-TU input fingerprints for `populate --incremental` (host-local, gitignored).
# Lets a dashboard refresh re-verify only the TUs whose inputs changed.
POPULATE_STATE_PATH = REPO_ROOT / "artifacts" / "audit" / "populate_state.json"
VC71_VERIFY = REPO_ROOT / "tools" / "verify" / "vc71_verify.py"

_LINE_RE = re.compile(
    r"(?:PASS|FAIL)\s+(\S+):\s+([\d.]+)%\s+match\s+\((\d+)/(\d+)\s+insns\)"
)
# vc71_verify emits one of these per compiled, kb.json-tracked function it could
# not score against any valid reference (no whole-object symbol and no valid
# per-function chunk).  These never produce a _LINE_RE score line, so the runner
# surfaces them separately to keep the re-delink queue complete.
_DROP_RE = re.compile(
    r"DROP\s+(\S+):\s+no valid reference\s+—\s+(.+?)\s+\(span\s+(\d+)\s+bytes\)"
)


# ---------------------------------------------------------------------------
# Baseline I/O
# ---------------------------------------------------------------------------

def load_baseline() -> dict[str, dict]:
    """Return {fn_name: {"score": float, "source": str}} from the baseline file."""
    if not BASELINE_PATH.exists():
        return {}
    try:
        data = json.loads(BASELINE_PATH.read_text())
        return data.get("scores", {})
    except (json.JSONDecodeError, OSError):
        return {}


def save_baseline(scores: dict[str, dict]) -> None:
    data = {"version": 1, "scores": scores}
    BASELINE_PATH.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def save_current(scores: dict[str, dict]) -> None:
    """Write honest current scores (dashboard source of truth)."""
    data = {"version": 1,
            "note": "Honest current VC71 scores, gated on reference validity. "
                    "Regenerated by `populate`; not a committed floor.",
            "scores": scores}
    CURRENT_PATH.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def save_validity(flagged: list[dict]) -> None:
    """Write the list of functions skipped because their reference failed
    validation (truncated/absent) — a re-delink work queue."""
    VALIDITY_PATH.parent.mkdir(parents=True, exist_ok=True)
    VALIDITY_PATH.write_text(
        json.dumps({"version": 1, "flagged": flagged}, indent=2, sort_keys=True) + "\n")


# ---------------------------------------------------------------------------
# Incremental populate: per-TU input fingerprints
# ---------------------------------------------------------------------------

def _sha_bytes(*chunks) -> str:
    h = hashlib.sha1()
    for c in chunks:
        if c is None:
            continue
        if isinstance(c, str):
            c = c.encode("utf-8", "replace")
        h.update(c)
        h.update(b"\0")
    return h.hexdigest()


def _sha_file(path: Path) -> str:
    try:
        return _sha_bytes(path.read_bytes())
    except OSError:
        return ""


_TOOL_EPOCH = None


def _tool_epoch() -> str:
    """Hash of every input shared by *all* TUs — the verify/compare tooling,
    kb.json (spans, names, aliases, ported flags), and the delinked per-function
    chunk directory (the fallback oracle).  When any of these change, the scoring
    semantics can move for any function, so a changed epoch forces a full
    re-verify.  This is what makes today's fold-fix (a tool change) correctly
    invalidate the whole cache while a lone source edit does not.
    """
    global _TOOL_EPOCH
    if _TOOL_EPOCH is not None:
        return _TOOL_EPOCH
    parts = []
    for rel in ("tools/verify/vc71_verify.py",
                "tools/verify/compare_obj.py",
                "tools/verify/vc71_regression.py",
                "tools/verify/vc71_cache.py",
                "kb.json"):
        parts.append(_sha_file(REPO_ROOT / rel))
    # Per-function chunk directory signature (name+size+mtime): a re-delink of
    # any fallback chunk must invalidate the cache.
    fdir = REPO_ROOT / "delinked" / "functions"
    sig = []
    if fdir.is_dir():
        for p in sorted(fdir.glob("*.obj")):
            try:
                st = p.stat()
                sig.append(f"{p.name}:{st.st_size}:{st.st_mtime_ns}")
            except OSError:
                continue
    parts.append(_sha_bytes("\n".join(sig)))
    _TOOL_EPOCH = _sha_bytes(*parts)
    return _TOOL_EPOCH


def _tu_fingerprint(src: Path, ref: Path) -> str:
    """Fingerprint one TU by its own inputs (source + whole-object reference).
    The tool/kb/chunk epoch is tracked separately at the state-file level."""
    return _sha_bytes(_sha_file(src), _sha_file(ref))


def load_populate_state() -> dict:
    if not POPULATE_STATE_PATH.exists():
        return {}
    try:
        return json.loads(POPULATE_STATE_PATH.read_text())
    except (json.JSONDecodeError, OSError):
        return {}


def save_populate_state(epoch: str, tus: dict) -> None:
    POPULATE_STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    data = {"version": 1, "tool_epoch": epoch, "tus": tus}
    POPULATE_STATE_PATH.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


# ---------------------------------------------------------------------------
# Reference-validity gate
# ---------------------------------------------------------------------------

_KB_MAPS = None


def _kb_maps():
    """Return (sorted_addrs, name->addr) from kb.json.

    Used to bound a function's expected instruction count against its byte span
    in the binary (next function start - this function start), so a truncated or
    bloated delinked reference can be detected before its score is trusted.
    """
    global _KB_MAPS
    if _KB_MAPS is None:
        addrs: set[int] = set()
        name2addr: dict[str, int] = {}
        try:
            data = json.loads((REPO_ROOT / "kb.json").read_text())
        except (OSError, json.JSONDecodeError):
            _KB_MAPS = ([], {})
            return _KB_MAPS
        for obj in data.get("objects", []):
            for fn in obj.get("functions") or []:
                a = fn.get("addr")
                if not a:
                    continue
                try:
                    ai = int(a, 16)
                except (ValueError, TypeError):
                    continue
                addrs.add(ai)
                name2addr[f"FUN_{ai:08x}"] = ai
                m = re.search(r"([A-Za-z_]\w*)\s*\(", fn.get("decl", "") or "")
                if m:
                    name2addr.setdefault(m.group(1), ai)
        _KB_MAPS = (sorted(addrs), name2addr)
    return _KB_MAPS


def _func_span(fn_name: str):
    """Byte span of a function (next function start - its start), or None."""
    addrs, name2addr = _kb_maps()
    addr = name2addr.get(fn_name)
    if addr is None:
        m = re.match(r"FUN_0*([0-9a-fA-F]+)$", fn_name)
        if m:
            addr = int(m.group(1), 16)
    if addr is None or not addrs:
        return None
    i = bisect.bisect_right(addrs, addr)
    return (addrs[i] - addr) if i < len(addrs) else None


def _reference_valid(n_r, span):
    """Whether a delinked reference is a usable byte-match oracle.

    A reference's instruction count must plausibly match the function's known
    byte size:
    - n_r * 15 (max x86 instruction length) < span  => truncated (too few insns
      to cover the function's bytes; e.g. a 144-byte function whose reference is
      a single instruction).
    - n_r > span                                     => bloated (more insns than
      bytes is impossible for real code — the reference swallowed neighbours).
    Both are hard bounds with no false positives on legitimately tiny functions
    (their span is small too).  Returns (ok: bool, reason: str).
    """
    if not n_r:
        return False, "reference symbol empty or absent"
    if span and n_r * 15 < span:
        return False, f"truncated reference: {n_r} insns cannot span {span} bytes"
    if span and n_r > span:
        return False, f"bloated reference: {n_r} insns exceed {span} bytes"
    return True, ""


# ---------------------------------------------------------------------------
# vc71_verify runner
# ---------------------------------------------------------------------------

def run_vc71_verify(source: Path, no_cache: bool = True,
                    function: str | None = None,
                    drops_out: list | None = None) -> dict[str, dict]:
    """Run vc71_verify on a source file; return {fn_name: {score, n_c, n_r}}.

    Defaults to --no-cache so stale .obj files from previous compilations do
    not mask source changes: vc71_verify's fast-path will read a stale .obj
    when the source hash misses the SQLite cache, producing phantom cache hits.
    The compile step is fast (~0.1s/file) so the accuracy cost is acceptable.

    If ``drops_out`` is provided, functions vc71_verify reported it could not
    score against any valid reference (DROP lines) are appended to it as
    ``{"function", "reason", "span_bytes"}`` dicts.  These never appear in the
    returned score dict — they exist only in ``drops_out``.
    """
    cmd = [sys.executable, str(VC71_VERIFY), str(source), "--quiet"]
    if function:
        cmd.extend(["--function", function])
    if no_cache:
        cmd.append("--no-cache")
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO_ROOT)
    out = {}
    for line in (result.stdout + result.stderr).splitlines():
        m = _LINE_RE.search(line)
        if m:
            out[m.group(1)] = {
                "score": float(m.group(2)),
                "n_c": int(m.group(3)),
                "n_r": int(m.group(4)),
            }
            continue
        if drops_out is not None:
            d = _DROP_RE.search(line)
            if d:
                drops_out.append({
                    "function": d.group(1),
                    "reason": d.group(2).strip(),
                    "span_bytes": int(d.group(3)),
                })
    return out


# ---------------------------------------------------------------------------
# update command
# ---------------------------------------------------------------------------

def _verify_source(src: Path, baseline: dict, force: bool):
    """Verify one source TU: apply the floor merge into ``baseline`` (in place)
    and return ``(n_changed, honest_slice, flagged_slice)`` for this TU only.

    - ``honest_slice``: ``{fn: {score, source, n_c, n_r}}`` for functions scored
      against a valid reference.
    - ``flagged_slice``: re-delink queue entries for this TU.

    Does not save the baseline — the caller saves once after all TUs.
    """
    honest_slice: dict = {}
    flagged_slice: list = []
    n_changed = 0

    print(f"Verifying {src.relative_to(REPO_ROOT)} ...", flush=True)
    drops: list = []
    results = run_vc71_verify(src, drops_out=drops)
    src_rel = str(src.relative_to(REPO_ROOT))

    # Functions vc71_verify could not score against any valid reference never
    # produce a score line, so the gate below never sees them.  Record them
    # directly in the re-delink queue so it is complete — not just the
    # gate-flagged (present-but-invalid-reference) subset.
    for d in sorted(drops, key=lambda x: x["function"]):
        flagged_slice.append({"function": d["function"], "source": src_rel,
                              "n_r": None, "span_bytes": d.get("span_bytes"),
                              "reason": d["reason"]})
        print(f"  ⚠ {d['function']}: no valid reference — {d['reason']}; "
              f"skipped (flagged for re-delink)")

    for fn_name, info in sorted(results.items()):
        new_score = info["score"]

        # Reference-validity gate: never trust a score computed against a
        # truncated/absent reference — skip it and flag for re-delink so a
        # broken reference cannot pollute the floor or the dashboard.
        n_r = info.get("n_r")
        span = _func_span(fn_name)
        ok, reason = _reference_valid(n_r, span)
        if not ok:
            flagged_slice.append({"function": fn_name, "source": src_rel,
                                  "n_r": n_r, "span_bytes": span,
                                  "reason": reason})
            print(f"  ⚠ {fn_name}: reference invalid — {reason}; "
                  f"skipped (flagged for re-delink)")
            continue

        honest_slice[fn_name] = {"score": new_score, "source": src_rel,
                                 "n_c": info.get("n_c"), "n_r": n_r}

        old_entry = baseline.get(fn_name)
        old_score = old_entry["score"] if old_entry else None

        if old_score is None:
            baseline[fn_name] = {"score": new_score, "source": src_rel}
            print(f"  + {fn_name}: {new_score:.1f}% (new)")
            n_changed += 1
        elif new_score > old_score + 0.1:
            # Improvement: always raise the floor
            baseline[fn_name] = {"score": new_score, "source": src_rel}
            print(f"  ↑ {fn_name}: {old_score:.1f}% → {new_score:.1f}%")
            n_changed += 1
        elif new_score < old_score - 0.1:
            if force:
                baseline[fn_name] = {"score": new_score, "source": src_rel}
                print(f"  ↓ {fn_name}: {old_score:.1f}% → {new_score:.1f}% (forced lower)")
                n_changed += 1
            else:
                print(f"  ! {fn_name}: {old_score:.1f}% → {new_score:.1f}%"
                      f" (drop; use --force to lower floor)")
        # else: unchanged within tolerance, nothing to do

    return n_changed, honest_slice, flagged_slice


def cmd_update(args, honest_out: dict | None = None,
               flagged_out: list | None = None) -> int:
    if not args.source:
        print("Error: --source is required for update.", file=sys.stderr)
        return 1

    baseline = load_baseline()
    total_changed = 0

    for src_str in args.source:
        src = Path(src_str)
        if not src.is_absolute():
            src = REPO_ROOT / src
        if not src.exists():
            print(f"  SKIP {src_str} (not found)", file=sys.stderr)
            continue

        n, honest_slice, flagged_slice = _verify_source(src, baseline, args.force)
        total_changed += n
        if honest_out is not None:
            honest_out.update(honest_slice)
        if flagged_out is not None:
            flagged_out.extend(flagged_slice)

    save_baseline(baseline)
    if total_changed:
        print(f"\nBaseline updated: {total_changed} function(s) changed → {BASELINE_PATH.name}")
    else:
        print("\nBaseline unchanged.")
    return 0


# ---------------------------------------------------------------------------
# check command
# ---------------------------------------------------------------------------

def cmd_check(args) -> int:
    threshold = args.threshold
    sources_filter = set(args.source) if args.source else None

    baseline = load_baseline()
    if not baseline:
        print("Baseline is empty. Run 'update' first.")
        return 0

    # Group baseline entries by source file
    by_source: dict[str, list[str]] = {}
    for fn_name, entry in baseline.items():
        src = entry.get("source", "")
        if sources_filter:
            # Accept both relative and absolute forms in the filter
            if src not in sources_filter and str(REPO_ROOT / src) not in sources_filter:
                continue
        by_source.setdefault(src, []).append(fn_name)

    if not by_source:
        print("No baseline entries match the given --source filter.")
        return 0

    regressions = []
    improvements = []
    skipped = 0
    ref_flagged = 0

    for src_rel, fn_names in sorted(by_source.items()):
        src_path = REPO_ROOT / src_rel
        if not src_path.exists():
            skipped += len(fn_names)
            if not args.quiet:
                print(f"  SKIP {src_rel} (file not found)")
            continue

        results = run_vc71_verify(src_path)

        for fn_name in fn_names:
            current = results.get(fn_name)
            if current is None:
                # Function not found in compiled output — may be unported or renamed
                continue
            # Reference-validity gate: a truncated/absent reference produces a
            # spuriously low current score.  Skip it (don't raise a false
            # regression) — it is tracked separately in the re-delink queue.
            ok, _ = _reference_valid(current.get("n_r"), _func_span(fn_name))
            if not ok:
                ref_flagged += 1
                if not args.quiet:
                    print(f"  ⚠ {fn_name}: reference invalid — skipped "
                          f"(flagged for re-delink, not a regression)")
                continue
            baseline_score = baseline[fn_name]["score"]
            current_score = current["score"]
            delta = current_score - baseline_score
            if delta < -threshold:
                regressions.append((fn_name, baseline_score, current_score, src_rel))
            elif delta > threshold and not args.quiet:
                improvements.append((fn_name, baseline_score, current_score, src_rel))

    if improvements:
        print(f"Improvements ({len(improvements)}):")
        for fn, base, curr, src in improvements:
            print(f"  ↑ {fn}: {base:.1f}% → {curr:.1f}% in {src}")
        print()

    if regressions:
        print(f"REGRESSIONS ({len(regressions)}):")
        for fn, base, curr, src in regressions:
            drop = base - curr
            print(f"  ✗ {fn}: {base:.1f}% → {curr:.1f}% (-{drop:.1f}pp) in {src}")
        print(
            "\nHint: investigate the change, fix the regression, then re-run:\n"
            "  python3 tools/verify/vc71_regression.py update --source <file>"
        )
        return 1

    checked = sum(len(v) for v in by_source.values()) - skipped - ref_flagged
    flagged_note = (f", {ref_flagged} skipped for invalid reference"
                    if ref_flagged else "")
    print(f"OK — no regressions ({checked} functions in "
          f"{len(by_source)} source file(s){flagged_note}).")
    return 0


# ---------------------------------------------------------------------------
# show command
# ---------------------------------------------------------------------------

def cmd_show(args) -> int:
    baseline = load_baseline()
    if not baseline:
        print("Baseline is empty.")
        return 0

    by_source: dict[str, list] = {}
    for fn_name, entry in baseline.items():
        by_source.setdefault(entry.get("source", "?"), []).append(
            (fn_name, entry["score"])
        )

    total = len(baseline)
    perfect = 0
    above90 = 0

    for src in sorted(by_source):
        fns = sorted(by_source[src], key=lambda x: x[1])
        print(f"\n{src}:")
        for fn_name, score in fns:
            marker = " ✓" if score >= 99.9 else ""
            print(f"  {fn_name:<44s} {score:6.1f}%{marker}")
            if score >= 99.9:
                perfect += 1
            if score >= 90.0:
                above90 += 1

    print(
        f"\nTotal: {total} functions | "
        f"{perfect} at 100% | {above90} at ≥90%"
    )
    return 0


# ---------------------------------------------------------------------------
# populate command
# ---------------------------------------------------------------------------

def cmd_populate(args) -> int:
    """Scan objdiff.json for source files with a delinked reference and refresh
    the floored baseline, the honest current scores, and the re-delink queue.

    With ``--incremental`` only TUs whose inputs changed since the last populate
    are re-verified; unchanged TUs carry their cached honest/flagged results
    forward (from ``populate_state.json``).  A change to the verify/compare
    tooling, kb.json, or the delinked chunk directory bumps the tool epoch and
    forces a full re-verify.  Without the flag, every TU is re-verified (the
    conservative default used by CI).
    """
    objdiff = REPO_ROOT / "objdiff.json"
    if not objdiff.exists():
        print("objdiff.json not found.", file=sys.stderr)
        return 1

    data = json.loads(objdiff.read_text())
    units = data.get("units", [])

    # Collect (src_abs, src_rel, ref_abs) for TUs whose reference exists on disk.
    tus = []
    seen = set()
    for unit in units:
        src = unit.get("metadata", {}).get("source_path", "")
        ref = unit.get("base_path", "")
        if not (src and ref):
            continue
        ref_abs = REPO_ROOT / ref
        full = REPO_ROOT / src
        if full.exists() and ref_abs.exists() and str(full) not in seen:
            seen.add(str(full))
            tus.append((full, str(Path(src)), ref_abs))

    if not tus:
        print("No source files with delinked references found in objdiff.json.")
        return 1

    incremental = getattr(args, "incremental", False)
    force = getattr(args, "force", False)
    epoch = _tool_epoch()
    prev = load_populate_state() if incremental else {}
    prev_ok = incremental and prev.get("tool_epoch") == epoch
    prev_tus = prev.get("tus", {}) if prev_ok else {}
    if incremental and prev and not prev_ok:
        print("Tool/kb.json/delinked epoch changed → full re-verify "
              "(incremental cache invalidated).")

    mode = "incremental" if incremental else "full"
    print(f"Populating baseline from {len(tus)} source files ({mode})...")

    baseline = load_baseline()
    honest: dict[str, dict] = {}
    flagged: list[dict] = []
    new_state: dict[str, dict] = {}
    total_changed = 0
    n_cached = 0
    n_verified = 0

    for src_abs, src_rel, ref_abs in tus:
        fp = _tu_fingerprint(src_abs, ref_abs)
        cached = prev_tus.get(src_rel)
        if cached and cached.get("fp") == fp:
            # Inputs unchanged since last populate → reuse this TU's results.
            # The floor is already correct (untouched); we only need to carry
            # the honest + flagged slices forward so the rewritten current/queue
            # files stay complete.
            for fn, rec in cached.get("honest", {}).items():
                honest[fn] = rec
            flagged.extend(cached.get("flagged", []))
            new_state[src_rel] = cached
            n_cached += 1
            continue

        n, honest_slice, flagged_slice = _verify_source(src_abs, baseline, force)
        total_changed += n
        honest.update(honest_slice)
        flagged.extend(flagged_slice)
        new_state[src_rel] = {
            "fp": fp,
            "ref": str(ref_abs.relative_to(REPO_ROOT)),
            "honest": honest_slice,
            "flagged": flagged_slice,
        }
        n_verified += 1

    save_baseline(baseline)
    if total_changed:
        print(f"\nBaseline updated: {total_changed} function(s) changed → {BASELINE_PATH.name}")
    else:
        print("\nBaseline unchanged.")

    # Honest current scores drive the dashboard; the floored baseline stays the
    # CI tripwire.  The validity report is the re-delink work queue.
    save_current(honest)
    save_validity(flagged)
    if incremental:
        save_populate_state(epoch, new_state)
        print(f"Incremental: {n_verified} TU(s) re-verified, {n_cached} cached "
              f"→ {POPULATE_STATE_PATH.relative_to(REPO_ROOT)}")
    print(f"\nHonest current scores: {len(honest)} functions → {CURRENT_PATH.name}")
    if flagged:
        print(f"Reference-validity: {len(flagged)} function(s) skipped "
              f"(broken/truncated reference) → {VALIDITY_PATH.relative_to(REPO_ROOT)}")
        print("  Re-delink these before their scores can be trusted:")
        for f in flagged[:12]:
            print(f"    {f['function']} ({f['source']}): {f['reason']}")
        if len(flagged) > 12:
            print(f"    ... and {len(flagged) - 12} more (see report)")
    return 0


# ---------------------------------------------------------------------------
# loadw command -- retroactive load-width (int vs int16/int8) sweep
# ---------------------------------------------------------------------------

def _discover_ref_sources() -> list[str]:
    """Source files that have a delinked reference (from objdiff.json)."""
    objdiff = REPO_ROOT / "objdiff.json"
    if not objdiff.exists():
        return []
    data = json.loads(objdiff.read_text())
    srcs = []
    for unit in data.get("units", []):
        src = unit.get("metadata", {}).get("source_path", "")
        ref = unit.get("base_path", "")
        if src and ref and (REPO_ROOT / ref).exists():
            full = REPO_ROOT / src
            if full.exists() and str(full) not in srcs:
                srcs.append(str(full))
    return srcs


def run_vc71_loadw(source: Path) -> list[str]:
    """Run vc71_verify --loadw-only on a source file; return the report lines
    (function headers + LOADW detail lines). Empty list means no load-width
    differences (or the file failed to compile/compare)."""
    cmd = [sys.executable, str(VC71_VERIFY), str(source),
           "--loadw-only", "--no-cache"]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO_ROOT)
    lines = []
    for line in (result.stdout + result.stderr).splitlines():
        s = line.rstrip()
        if "[LOADW-WARN]" in s or s.strip().startswith("LOADW:"):
            lines.append(s)
    return lines


def cmd_loadw(args) -> int:
    """Sweep every source file with a delinked reference for load-width
    (int vs int16_t/int8_t) differences and write a report. This finds the
    same class as the c10 tag_groups:3089 pg_surf crash across the whole tree.
    """
    if args.source:
        sources = [str(REPO_ROOT / s if not Path(s).is_absolute() else s)
                   for s in args.source]
    else:
        sources = _discover_ref_sources()
    if not sources:
        print("No source files with delinked references found.", file=sys.stderr)
        return 1

    out_path = REPO_ROOT / "artifacts" / "audit" / "loadw_sweep.txt"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    total_hits = 0
    files_with_hits = 0
    report = []
    print(f"Sweeping {len(sources)} source file(s) for load-width differences...\n",
          flush=True)
    for src_str in sorted(sources):
        src = Path(src_str)
        rel = src.relative_to(REPO_ROOT) if src.is_absolute() and str(src).startswith(str(REPO_ROOT)) else src
        lines = run_vc71_loadw(src)
        hits = [l for l in lines if l.strip().startswith("LOADW:")]
        if lines:
            files_with_hits += 1
            total_hits += len(hits)
            header = f"=== {rel} ({len(hits)} finding(s)) ==="
            print(header, flush=True)
            for l in lines:
                print(l)
            report.append(header)
            report.extend(lines)
            report.append("")

    summary = (f"\nLoad-width sweep: {total_hits} finding(s) across "
               f"{files_with_hits}/{len(sources)} file(s).")
    print(summary)
    out_path.write_text("\n".join(report) + summary + "\n")
    print(f"Report written to {out_path.relative_to(REPO_ROOT)}")
    print("NOTE: findings are review items -- verify each against disassembly "
          "(a narrow field read wide, or vice versa) before any fix.")
    return 0


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = ap.add_subparsers(dest="command")

    p_update = sub.add_parser("update", help="Update baseline for source file(s)")
    p_update.add_argument("--source", "-s", nargs="+",
                          help="Source .c file(s) to run vc71_verify on")
    p_update.add_argument("--force", action="store_true",
                          help="Allow lowering stored floors (normally disallowed)")

    p_check = sub.add_parser("check", help="Check for regressions against baseline")
    p_check.add_argument("--source", "-s", nargs="+",
                         help="Limit check to these source files")
    p_check.add_argument("--threshold", "-t", type=float, default=2.0,
                         help="Acceptable drop in pp before flagging (default: 2.0)")
    p_check.add_argument("--quiet", "-q", action="store_true",
                         help="Suppress improvement messages")

    sub.add_parser("show", help="Display current baseline")

    p_pop = sub.add_parser("populate",
                           help="Populate baseline for all objdiff.json source files")
    p_pop.add_argument("--force", action="store_true",
                       help="Allow lowering floored baseline to honest scores "
                            "(one-time rebaseline after reference/measurement fixes)")
    p_pop.add_argument("--incremental", action="store_true",
                       help="Only re-verify TUs whose source or reference changed "
                            "since the last populate (state in "
                            "artifacts/audit/populate_state.json). A tooling, "
                            "kb.json, or delinked-chunk change forces a full pass.")

    p_loadw = sub.add_parser("loadw",
                             help="Sweep for load-width (int vs int16/int8) differences")
    p_loadw.add_argument("--source", "-s", nargs="+",
                         help="Limit sweep to these source files (default: all with a ref)")

    args = ap.parse_args()

    if args.command == "update":
        sys.exit(cmd_update(args))
    elif args.command == "check":
        sys.exit(cmd_check(args))
    elif args.command == "show":
        sys.exit(cmd_show(args))
    elif args.command == "populate":
        sys.exit(cmd_populate(args))
    elif args.command == "loadw":
        sys.exit(cmd_loadw(args))
    else:
        ap.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
