//Rename FUN_* functions to known names from kb.json (only if auto-named)
//@category Analysis
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import ghidra.program.model.symbol.SourceType;
import java.util.*;

public class RenameFromKB extends GhidraScript {
    @Override
    public void run() throws Exception {
        Map<String, String> kb = new LinkedHashMap<>();
        kb.put("0x100090","sort_desired_local_player_controllers");
        kb.put("0x1000d0","create_local_players");
        kb.put("0x100590","main_queue_map_name");
        kb.put("0x100640","main_menu_precache_resources");
        kb.put("0x100910","compute_window_bounds");
        kb.put("0x100b40","main_new_map");
        kb.put("0x100c10","main_change_map_name");
        kb.put("0x100de0","main_skip_private");
        kb.put("0x100eb0","main_save_map_private");
        kb.put("0x101040","main_won_map_private");
        kb.put("0x101130","main_frame_rate_debug");
        kb.put("0x1013d0","main_update_time");
        kb.put("0x101cd0","main_vertical_blank_interrupt_handler");
        kb.put("0x105770","shell_initialize");
        kb.put("0x105a60","shell_dispose");
        kb.put("0x105c80","shell_update");
        kb.put("0x1188c0","cs_stricmp");
        kb.put("0x118900","cs_strnicmp");
        kb.put("0x118d90","cs_parsing_error");
        kb.put("0x119a60","datum_new");
        kb.put("0x119ac0","datum_delete");
        kb.put("0x119320","datum_get");
        kb.put("0x1194d0","data_new");
        kb.put("0x1194f0","data_dispose");
        kb.put("0x119580","data_make_valid");
        kb.put("0x119620","data_is_valid");
        kb.put("0x119690","data_next_index");
        kb.put("0x119720","data_actual_to_index");
        kb.put("0x1197a0","data_name_to_index");
        kb.put("0x119810","data_iterator_next");
        kb.put("0x11a530","object_list_begin");
        kb.put("0x11a590","object_list_end");
        kb.put("0x3aa50","actors_dispose");
        kb.put("0x3aa90","actors_dispose_from_old_map");
        kb.put("0x3aae0","actors_initialize_for_new_map");
        kb.put("0x3f670","ai_initialize");
        kb.put("0x3f6f0","ai_dispose");
        kb.put("0x3f720","ai_dispose_from_old_map");
        kb.put("0x3f760","ai_place");
        kb.put("0x41090","ai_initialize_for_new_map");
        kb.put("0x41180","ai_update");
        kb.put("0x42390","ai_clump");
        kb.put("0x425a0","ai_enemies_can_see_player");
        kb.put("0x42b80","FUN_00042b80");
        kb.put("0x42ca0","FUN_00042ca0");
        kb.put("0x42e50","ai_try_fight");
        kb.put("0x42f10","ai_try_fight_from_vehicle");
        kb.put("0x48f50","FUN_00048f50");
        kb.put("0x48fa0","FUN_00048fa0");
        kb.put("0x53640","FUN_00053640");
        kb.put("0x7c8f0","editor_editing_sandbox");
        kb.put("0x7c930","editor_sandbox");
        kb.put("0x7c970","editor_selection");
        kb.put("0x7c990","editor_object_at_marker");
        kb.put("0x7c9b0","editor_object_marker");
        kb.put("0x7c9d0","editor_unit_in_vehicle");
        kb.put("0x7c9f0","editor_position");
        kb.put("0x7ca10","editor_team");
        kb.put("0x7ca30","editor_bsp");
        kb.put("0x7ca50","editor_rotation");
        kb.put("0x7ca70","editor_multiplayer_spawn");
        kb.put("0x82130","observer_initialize");
        kb.put("0x82280","observer_dispose");
        kb.put("0x82bb0","observer_update");
        kb.put("0x89280","observer_look_at_point");
        kb.put("0x8a4e0","observer_get_camera");
        kb.put("0x8c730","director_initialize");
        kb.put("0x8c7d0","director_dispose");
        kb.put("0x8c870","director_update");
        kb.put("0x8c930","director_do_machine_migration");
        kb.put("0x8c9b0","director_end");
        kb.put("0x8ca00","director_get_player");
        kb.put("0x8ca50","director_get_unit");
        kb.put("0x8cab0","director_get_observing_player");
        kb.put("0x8cb80","director_submit_animation_target");
        kb.put("0x8cc60","director_submit_unit_target");
        kb.put("0x8cd40","director_submit_engine_notification");
        kb.put("0x8d9d0","csprintf");
        kb.put("0x8db80","csmemset");
        kb.put("0x8de70","csstrncpy");
        kb.put("0x8e0b0","csmemcpy");
        kb.put("0x8e2f0","cs_exit");
        kb.put("0x8e820","debug_memory_walk_stack");
        kb.put("0x8ee60","debug_malloc");
        kb.put("0x9f680","input_initialize");
        kb.put("0x9f6a0","input_dispose");
        kb.put("0x9f710","input_get_binding");
        kb.put("0x9f8a0","input_get_bindings_count");
        kb.put("0x9f930","input_get_binding_id");
        kb.put("0xa2690","player_effect_get");
        kb.put("0xa74c0","game_set_game_engine_index");
        kb.put("0xa8220","game_engine_evaluate_game_complexity");
        kb.put("0xa8260","game_engine_get_random_seed");
        kb.put("0xa8280","game_engine_get_game_variant");
        kb.put("0xa82a0","game_engine_is_team_game");
        kb.put("0xa82c0","game_engine_is_multiplayer");
        kb.put("0xa82d0","game_engine_rules");
        kb.put("0xa82e0","game_engine_widget_event");
        kb.put("0xa82f0","game_engine_render_effects");
        kb.put("0xa8300","game_engine_area_in_vehicle");
        kb.put("0xa8320","game_engine_bsp");
        kb.put("0xa8340","game_engine_section");
        kb.put("0xa8360","game_engine_is_units_enemy");
        kb.put("0xa8380","game_engine_actor_speed");
        kb.put("0xa8c30","game_engine_can_object_move_in_direction");
        kb.put("0xa8c80","game_engine_unit_in_weapon_range");
        kb.put("0xa9030","game_engine_player_unit_in_vehicle");
        kb.put("0xa9090","game_engine_get_material_effective_owner");
        kb.put("0xa9110","game_engine_unit_has_bonus");
        kb.put("0xa9170","game_engine_start");
        kb.put("0xab310","game_engine_end");
        kb.put("0xac310","game_engine_determine_winner");
        kb.put("0xacdd0","game_engine_update_non_deterministic");
        kb.put("0xae760","game_engine_initialize_for_new_map");
        kb.put("0xaf370","game_engine_update");
        kb.put("0xb0020","game_variant_get_random_skull");
        kb.put("0xb0950","cheats_initialize");
        kb.put("0xb0960","cheats_dispose");
        kb.put("0xb0970","cheats_load");
        kb.put("0xb0980","cheats_dispose_from_old_map");
        kb.put("0xb0990","cheats_apply");
        kb.put("0xb5990","game_time_initialized");
        kb.put("0xb59b0","game_time_get");
        kb.put("0xb59c0","game_time_get_elapsed");
        kb.put("0xb59d0","game_ticks_difference");
        kb.put("0xb59e0","game_time_to_ticks");
        kb.put("0xb59f0","game_ticks_to_time");
        kb.put("0xb5a00","game_seconds_to_ticks");
        kb.put("0xb5a10","game_ticks_to_seconds");
        kb.put("0xb5a20","game_time_get_real_time");
        kb.put("0xb5a30","game_time_set");
        kb.put("0xb5a50","game_time_update");
        kb.put("0xb5b00","game_time_footer");
        kb.put("0xb5b60","local_time_get_elapsed");
        kb.put("0xb5ba0","game_predicting");
        kb.put("0xb5bc0","game_time_advance");
        kb.put("0xb5c10","game_time_pause");
        kb.put("0xb5c50","game_time_resume");
        kb.put("0xb5cc0","game_time_get_rate");
        kb.put("0xb5cd0","game_time_set_rate");
        kb.put("0xb5ce0","game_time_debug_render");
        kb.put("0xb5d50","game_time_statistics_new");
        kb.put("0xb5e50","game_time_globals_resize");
        kb.put("0xb66a0","game_allegiance_initialize");
        kb.put("0xb66b0","game_allegiance_dispose");
        kb.put("0xb66c0","game_allegiance_initialize_for_new_map");
        kb.put("0xb66d0","game_allegiance_team");
        kb.put("0xb66e0","game_allegiance_lookup");
        kb.put("0xb6700","game_allegiance_is_enemy");
        kb.put("0xba270","machine_get_player_list");
        kb.put("0xba290","player_register_machine");
        kb.put("0xba6b0","players_get_combined_pvs_local");
        kb.put("0xba6c0","players_get_combined_pvs");
        kb.put("0xba710","any_player_is_in_the_air");
        kb.put("0xbadf0","players_compute_local_player_count");
        kb.put("0xbae20","player_examine_nearby_unit");
        kb.put("0xbaeb0","player_reset_action_result");
        kb.put("0xbaed0","player_try_to_enter_vehicle");
        kb.put("0xbaf80","player_action_result");
        kb.put("0xbb040","player_location");
        kb.put("0xbb0a0","player_get_identifier");
        kb.put("0xbb2f0","player_new");
        kb.put("0xbb380","player_delete");
        kb.put("0xbb480","player_update");
        kb.put("0xbb560","player_build_action_update");
        kb.put("0xbbe00","player_get_action_update");
        kb.put("0xbc0d0","player_try_to_spawn_in_vehicle");
        kb.put("0xbcfb0","player_set_action_result_for_vehicle");
        kb.put("0xbd090","player_control_initialize");
        kb.put("0xbd0a0","player_control_dispose");
        kb.put("0xbd0b0","player_control_update");
        kb.put("0xbd120","player_control_look_update_x");
        kb.put("0xbd190","player_control_look_update_y");
        kb.put("0xbd6e0","player_control_get_mapping_type");
        kb.put("0xbc750","players_respawn_coop");
        kb.put("0xbe400","player_rumble_initialize");
        kb.put("0xbe410","player_rumble_dispose");
        kb.put("0xbe420","player_rumble_update");
        kb.put("0xbe580","player_rumble_set_intensity");
        kb.put("0xbe770","player_rumble_set_effect");
        kb.put("0xbe830","player_rumble_set_enabled");
        kb.put("0xbe930","player_effect_initialize");
        kb.put("0xbe950","player_effect_dispose");
        kb.put("0xbe960","player_effect_update");
        kb.put("0xbeb10","player_effect_start");
        kb.put("0xbee50","player_effect_wait_for_player");
        kb.put("0xcf710","input_get_gamepad_state");
        kb.put("0xcf850","input_get_gamepad_state2");
        kb.put("0xcfa00","input_abstraction_initialize");
        kb.put("0xcfb60","input_abstraction_dispose");
        kb.put("0xcfb70","input_abstraction_update");
        kb.put("0xd0ba0","hud_get_item_string");
        kb.put("0xd0c70","hud_set_element_count");
        kb.put("0xd0c80","hud_set_element_digital");
        kb.put("0xd0cb0","hud_set_element_analog");
        kb.put("0xd0cc0","hud_set_element_vector");
        kb.put("0xd0cf0","hud_set_element_text");
        kb.put("0xd5120","scripted_hud_messages_clear");
        kb.put("0xd5140","scripted_hud_messages_initialize");
        kb.put("0xd5180","scripted_hud_messages_dispose");
        kb.put("0xd51c0","scripted_hud_messages_update");
        kb.put("0xd5380","scripted_hud_messaging_initialize");
        kb.put("0xd5390","scripted_hud_messaging_dispose");
        kb.put("0xd53a0","scripted_hud_messaging_update");
        kb.put("0xd54c0","scripted_hud_messaging_render");
        kb.put("0xe1c70","progress_bar_initialize");
        kb.put("0xe1c80","progress_bar_dispose");
        kb.put("0xe1c90","progress_bar_begin");
        kb.put("0xe1cc0","progress_bar_end");
        kb.put("0xe3300","progress_bar_display");
        kb.put("0xe3be0","ui_widgets_initialize");
        kb.put("0xe4470","ui_widget_load_progress_widget");
        kb.put("0xe58c0","ui_widgets_close_all");
        kb.put("0xe6a60","ui_widgets_dispose");
        kb.put("0xe8700","main_screen_shell_load");
        kb.put("0xe8d20","display_error_damaged_media");
        kb.put("0xff400","console_initialize");
        kb.put("0xff460","console_initialize_for_new_map");
        kb.put("0xff550","console_warning");
        kb.put("0xff8a0","console_startup");
        kb.put("0xff9c0","console_dispose");
        kb.put("0xffa10","console_write_line");
        kb.put("0x1013d0","main_update_time");
        kb.put("0x101cd0","main_vertical_blank_interrupt_handler");
        kb.put("0x102b30","main_initialize");
        kb.put("0x104000","main_dispose");
        kb.put("0x104310","main_game_loop");
        kb.put("0x104510","main");
        kb.put("0x10b0d0","get_global_random_seed_address");
        kb.put("0x119320","datum_get");
        kb.put("0x1194d0","data_new");
        kb.put("0x119810","data_iterator_next");
        kb.put("0x13d680","object_get_and_verify_type");
        kb.put("0x18e380","global_scenario_get");
        kb.put("0x18e3c0","scenario_get");
        kb.put("0x18e450","game_globals_get");
        kb.put("0x1999f0","file_reference_create_from_path");
        kb.put("0x19b210","tag_block_get_element");
        kb.put("0x19dc90","ustrncpy");
        kb.put("0x19f450","ascii_to_wide");
        kb.put("0x1a1e90","bink_playback_initialize");
        kb.put("0x1a1ea0","bink_playback_dispose");
        kb.put("0x1a1eb0","bink_playback_update");
        kb.put("0x1a1ec0","bink_playback_render");
        kb.put("0x1a7ff0","units_update");
        kb.put("0x1aa3c0","any_unit_is_dangerous");
        kb.put("0x1aac40","unit_clear_seat_tag");
        kb.put("0x1ae600","unit_set_in_vehicle");
        kb.put("0x1af990","unit_set_control");
        kb.put("0x1ba140","tag_get");
        kb.put("0x1bfbf0","game_state_malloc");
        kb.put("0x1bfe10","game_state_data_new");
        kb.put("0x1cf730","sound_render");
        kb.put("0x12a1e0","dispose_global_network_game_client");
        kb.put("0x12a210","network_game_server_start_frame");
        kb.put("0x12a2a0","dispose_global_network_game_server");
        kb.put("0x12a2d0","network_game_client_start_frame");
        kb.put("0x12a500","network_game_client_end_frame");
        kb.put("0x15b190","rasterizer_decals_initialize_for_new_map");
        kb.put("0x15b1a0","rasterizer_decals_dispose_from_old_map");
        kb.put("0x15b6d0","rasterizer_decals_initialize");
        kb.put("0x15b7e0","rasterizer_decals_dispose");

        FunctionManager fm = currentProgram.getFunctionManager();
        int renamed = 0;
        int skipped = 0;
        int notFound = 0;

        for (Map.Entry<String, String> entry : kb.entrySet()) {
            long addr = Long.parseLong(entry.getKey().substring(2), 16);
            String newName = entry.getValue();
            ghidra.program.model.address.Address funcAddr =
                currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(addr);
            Function func = fm.getFunctionAt(funcAddr);
            if (func == null) {
                notFound++;
                continue;
            }
            String curName = func.getName();
            if (curName.startsWith("FUN_")) {
                func.setName(newName, SourceType.USER_DEFINED);
                renamed++;
                println("Renamed 0x" + Long.toHexString(addr) + " " + curName + " -> " + newName);
            } else {
                skipped++;
            }
        }

        println("Done. Renamed: " + renamed + " | Skipped (already named): " + skipped + " | Not found: " + notFound);
    }
}
